package com.squidgame.game.redlight;

import com.squidgame.build.Marker;
import com.squidgame.build.Region;
import com.squidgame.core.GameKind;
import com.squidgame.core.redlight.DollCycle;
import com.squidgame.core.redlight.RedLightRules;
import com.squidgame.core.redlight.StartOrder;
import com.squidgame.core.util.Rng;
import com.squidgame.entity.Activity;
import com.squidgame.entity.ContestantEntity;
import com.squidgame.entity.DollEntity;
import com.squidgame.game.EliminationCause;
import com.squidgame.game.GameContext;
import com.squidgame.game.GameResult;
import com.squidgame.game.MiniGame;
import com.squidgame.net.HudPayload;
import com.squidgame.registry.ModEntities;
import com.squidgame.registry.ModSounds;
import com.squidgame.tournament.Contestant;
import com.squidgame.tournament.Teleporter;
import net.minecraft.network.chat.Component;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.sounds.SoundSource;
import net.minecraft.util.Mth;
import net.minecraft.world.entity.LivingEntity;
import net.minecraft.world.phys.Vec3;
import org.jetbrains.annotations.Nullable;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Red Light, Green Light. Cross the field to the finish line; the giant doll chants with her back turned
 * (GREEN: move freely), turns when the chant ends (TURNING: the stopping allowance) and then, with glowing eyes
 * (RED), eliminates anything that moves. The same {@link RedLightRules} judge players and NPCs.
 *
 * <p>Timeline per cycle is generated by {@link DollCycle}. Everything an NPC may know is exposed through
 * {@link PublicView}; NPCs never see the cycle that has not happened yet.
 */
public final class RedLightGreenLightGame implements MiniGame {
    /** Observable facts about the doll, usable by humans and NPCs alike. */
    public final class PublicView {
        /** Current light, as it can be observed (chanting / turning / eyes lit). */
        public DollCycle.Light light() {
            return light;
        }

        /** Number of syllables of the chant that have been sung so far in this cycle (0-10). */
        public int syllablesHeard() {
            return syllablesSung;
        }

        /** Server tick at which each heard syllable began (index i = syllable i); valid up to syllablesHeard(). */
        public long syllableStartTick(int i) {
            return syllableTicks[i];
        }

        public long cycleStartTick() {
            return cycleStartTick;
        }

        public long lightChangedTick() {
            return lightChangedTick;
        }

        public boolean eyesLit() {
            return light == DollCycle.Light.RED;
        }

        /** The finish line z coordinate (public: the line is painted on the ground). */
        public double finishZ() {
            return finishZ;
        }

        public double startZ() {
            return startZ;
        }

        public Region field() {
            return fieldRegion;
        }

        public Region safeZone() {
            return safeRegion;
        }

        public long lastShotTick() {
            return lastShotTick;
        }

        public Vec3 lastShotPos() {
            return lastShotPos;
        }

        public int allowanceTicks() {
            return RedLightRules.params(difficulty).allowanceTicks();
        }

        /** The server game time: the time base of every tick value this view exposes (cycle start, syllables, light changes, shots). */
        public long now() {
            return levelNow;
        }
    }

    private static final int INTRO_TICKS = 50;

    private final PublicView view = new PublicView();
    private final Rng rng = new Rng(0);
    private com.squidgame.core.Difficulty difficulty = com.squidgame.core.Difficulty.NORMAL;
    private RedLightRules.Params params;
    private DollEntity doll;
    private DollCycle cycle;
    private int cycleTick;
    private int cycleIndex;
    private DollCycle.Light light = DollCycle.Light.GREEN;
    private int syllablesSung;
    private final long[] syllableTicks = new long[DollCycle.SYLLABLES];
    private long cycleStartTick;
    private long lightChangedTick;
    private long gameClock;
    /** Server game time of the current tick (same base as {@code cycleStartTick}, {@code lightChangedTick}...). */
    private long levelNow;
    private double startZ, finishZ;
    private Region fieldRegion, safeRegion;
    private Vec3 dollPos = Vec3.ZERO;
    private float dollYaw;
    private boolean started;
    private long lastShotTick = -1000;
    private Vec3 lastShotPos = Vec3.ZERO;
    private Rng cycleRng;

    /** Per-contestant tracking for the movement rule. */
    private static final class Track {
        Vec3 last;
        boolean airborneAtWatch;
        boolean finished;
        boolean condemned;
        int bestZ;
    }

    private final Map<Integer, Track> tracks = new HashMap<>();
    private final Set<Integer> finishedOrder = new HashSet<>();
    private int finishCounter;

    public PublicView view() {
        return view;
    }

    /** Difficulty used for NPC skill (the NPC behaviour is created after prepare). */
    public com.squidgame.core.Difficulty difficultyForNpc() {
        return difficulty;
    }

    @Override
    public GameKind type() {
        return GameKind.RED_LIGHT;
    }

    @Override
    public List<Component> instructions(GameContext ctx) {
        RedLightRules.Params p = RedLightRules.params(ctx.difficulty());
        String allowance = String.format("%.1f", p.allowanceTicks() / 20.0);
        return List.of(
                Component.translatable("squidgame.game.red_light.instruction.1"),
                Component.translatable("squidgame.game.red_light.instruction.2"),
                Component.translatable("squidgame.game.red_light.instruction.3", allowance),
                Component.translatable("squidgame.game.red_light.instruction.4"),
                Component.translatable("squidgame.game.red_light.instruction.5"),
                Component.translatable("squidgame.game.red_light.instruction.6", ctx.difficulty().id));
    }

    @Override
    public Component objective(GameContext ctx, @Nullable Contestant viewer) {
        if (viewer != null) {
            Track t = tracks.get(viewer.number);
            if (t != null && t.finished) {
                return Component.translatable("squidgame.game.red_light.objective.safe");
            }
        }
        return Component.translatable("squidgame.game.red_light.objective");
    }

    @Override
    public int timeLimitTicks(GameContext ctx) {
        double seconds = switch (ctx.difficulty()) {
            case NORMAL -> 200;
            case HARD -> 185;
            case EXTREME -> 165;
        };
        return (int) (seconds * 20);
    }

    // ------------------------------------------------------------------ lifecycle

    @Override
    public void prepare(GameContext ctx) {
        difficulty = ctx.difficulty();
        params = RedLightRules.params(difficulty);
        cycleRng = ctx.rng().fork(77);
        tracks.clear();
        finishedOrder.clear();
        finishCounter = 0;
        started = false;
        Region fl = ctx.region("redlight.finish_line");
        Region sl = ctx.region("redlight.start_line");
        startZ = sl != null ? sl.maxZ() + 1 : 12;
        finishZ = fl != null ? fl.maxZ() + 1 : 141;
        fieldRegion = ctx.region("arena.bounds");
        safeRegion = ctx.region("redlight.safe_zone");
        Marker dm = ctx.marker("redlight.doll");
        if (dm != null) {
            dollPos = new Vec3(dm.x(), dm.y(), dm.z());
            dollYaw = dm.yaw();
        } else {
            dollPos = new Vec3(0.5, 65, finishZ + 6);
            dollYaw = 0f;
        }
        doll = ModEntities.DOLL.create(ctx.level);
        if (doll != null) {
            doll.moveTo(dollPos.x, dollPos.y, dollPos.z, dollYaw, 0f);
            doll.setYBodyRot(dollYaw);
            doll.setYHeadRot(dollYaw);
            doll.addTag("squidgame_temp");
            doll.setState(DollEntity.State.DORMANT);
            doll.setEyes(false);
            doll.setTurnTicks(params.dollTurnTicks());
            ctx.level.getChunk(doll.blockPosition());
            ctx.level.addFreshEntity(doll);
        }
        ctx.spawnGuards();
    }

    @Override
    public void placeContestants(GameContext ctx) {
        List<Marker> slots = ctx.markers("redlight.start_spawn");
        double[] sx = new double[slots.size()], sz = new double[slots.size()];
        for (int i = 0; i < slots.size(); i++) {
            sx[i] = slots.get(i).x();
            sz[i] = slots.get(i).z();
        }
        Teleporter.spread(ctx.level, StartOrder.humansIntoCrowd(ctx.alive(), Contestant::isHumanControlled, sx, sz), slots);
        for (Contestant c : ctx.alive()) {
            ContestantEntity e = ctx.npc(c);
            if (e != null) {
                e.setActivity(Activity.NONE);
            }
        }
    }

    @Override
    public void begin(GameContext ctx) {
        started = true;
        gameClock = 0;
        levelNow = ctx.now();
        for (Contestant c : ctx.alive()) {
            Track t = new Track();
            LivingEntity b = c.body(ctx.level);
            t.last = b == null ? null : b.position();
            tracks.put(c.number, t);
        }
        if (doll != null) {
            doll.setState(DollEntity.State.FACING_TREE);
        }
        ctx.doors().close(ctx.level, "gate");
        ctx.assignBehaviors(c -> new RedLightNpcBehavior(this, c));
        // the doll needs a moment before the first chant
        cycle = null;
        cycleTick = -INTRO_TICKS;
        cycleIndex = 0;
        light = DollCycle.Light.GREEN;
        lightChangedTick = 0;
    }

    @Override
    public void onControllerChanged(GameContext ctx, Contestant c) {
        ContestantEntity e = ctx.npc(c);
        if (e != null && started && c.isAlive()) {
            e.setBehavior(new RedLightNpcBehavior(this, c));
        }
        Track t = tracks.get(c.number);
        if (t != null) {
            t.last = null;
        }
    }

    // ------------------------------------------------------------------ tick

    @Override
    public void tick(GameContext ctx) {
        gameClock++;
        levelNow = ctx.now();
        tickDoll(ctx);
        long now = ctx.now();
        boolean watched = light == DollCycle.Light.RED;
        for (Contestant c : ctx.alive()) {
            Track t = tracks.get(c.number);
            if (t == null) {
                continue;
            }
            LivingEntity body = c.body(ctx.level);
            if (body == null) {
                continue;
            }
            Vec3 pos = body.position();
            Vec3 last = t.last;
            t.last = pos;
            if (!t.finished && pos.z >= finishZ && pos.z < finishZ + 60) {
                finish(ctx, c, t);
                continue;
            }
            if (t.finished || t.condemned || last == null) {
                continue;
            }
            if (!watched) {
                continue;
            }
            RedLightRules.Verdict v = RedLightRules.evaluate(params, true, t.airborneAtWatch, sample(c, body, pos, last));
            if (v.isViolation()) {
                condemn(ctx, c, t, body, v);
            }
        }
    }

    private RedLightRules.Sample sample(Contestant c, LivingEntity body, Vec3 pos, Vec3 last) {
        double dx = pos.x - last.x, dz = pos.z - last.z;
        double h = Math.sqrt(dx * dx + dz * dz);
        double v = pos.y - last.y;
        boolean input;
        boolean jump;
        if (body instanceof ServerPlayer sp) {
            input = Math.abs(sp.xxa) > 0.01f || Math.abs(sp.zza) > 0.01f;
            jump = sp.jumping;
        } else if (body instanceof ContestantEntity npc) {
            input = npc.isTryingToMove();
            jump = false;
        } else {
            input = false;
            jump = false;
        }
        boolean external = body.hurtTime > 0 || body.isPassenger() || body.isInWater() || body.isInLava() || body.isFallFlying();
        return new RedLightRules.Sample(h, v, body.onGround(), input, jump, external);
    }

    private void finish(GameContext ctx, Contestant c, Track t) {
        t.finished = true;
        finishedOrder.add(c.number);
        c.stats.put("finishRank", (double) (++finishCounter));
        c.stats.put("finishTick", (double) gameClock);
        ContestantEntity e = ctx.npc(c);
        if (e != null && c.isAiControlled()) {
            // NPC behaviour switches to the safe-zone routine on its own (it checks the finish line too)
            e.triggerAction("relieved");
        }
        ServerPlayer p = c.player(ctx.server());
        if (p != null && c.isHumanControlled()) {
            ctx.sound(ModSounds.UI_CONFIRM, 1f, 1.2f);
            p.displayClientMessage(Component.translatable("squidgame.game.red_light.crossed", finishCounter), true);
        }
    }

    private void condemn(GameContext ctx, Contestant c, Track t, LivingEntity body, RedLightRules.Verdict v) {
        t.condemned = true;
        lastShotTick = ctx.now();
        lastShotPos = body.position();
        if (doll != null) {
            doll.lockOn();
        }
        ctx.sound(ModSounds.DOLL_LOCK_ON, 0.5f, 1f);
        int aim = 8 + ctx.rng().nextInt(8);
        ctx.eliminateByGuard(c, aim);
        ctx.config();
        com.squidgame.SquidGameMod.debug("RLGL: {} eliminated ({}), {} ticks into red, speed {}/tick, cycle {}", c.label(), v,
                ctx.now() - lightChangedTick, String.format("%.3f", body.getDeltaMovement().horizontalDistance()), cycleIndex);
    }

    // ------------------------------------------------------------------ doll driving

    private void tickDoll(GameContext ctx) {
        if (doll == null || !started) {
            return;
        }
        cycleTick++;
        if (cycleTick < 0) {
            return;
        }
        if (cycle == null) {
            newCycle(ctx, 0.0);
        }
        // the doll finishes turning back to the tree during the first moments of the next chant
        if (doll.state() == DollEntity.State.TURNING_TO_TREE && cycleTick >= params.dollTurnTicks()) {
            doll.setState(DollEntity.State.FACING_TREE);
        }
        // syllables
        int idx = cycle.syllableAt(cycleTick);
        if (idx >= 0 && idx == syllablesSung && cycleTick >= cycle.syllableStart[idx]) {
            syllableTicks[idx] = ctx.now();
            int interval = cycle.syllableStart[idx + 1] - cycle.syllableStart[idx];
            float pitch = Mth.clamp(9.0f / Math.max(3, interval), 0.85f, 1.7f);
            ctx.soundAt(dollPos.add(0, 6, 0), ModSounds.DOLL_SYLLABLES[idx], SoundSource.NEUTRAL, 9f, pitch);
            syllablesSung++;
            if (idx == 0 && doll.state() != DollEntity.State.FACING_TREE && doll.state() != DollEntity.State.TURNING_TO_TREE) {
                doll.setState(DollEntity.State.FACING_TREE);
            }
        }
        if (cycleTick == cycle.chantTicks) {
            // the chant ends: the doll starts to turn; the stopping allowance runs
            setLight(ctx, DollCycle.Light.TURNING);
            doll.setTurnTicks(params.dollTurnTicks());
            doll.setScanning(false);
            doll.setState(DollEntity.State.TURNING_TO_PLAYERS);
            ctx.soundAt(dollPos.add(0, 6, 0), ModSounds.DOLL_TURN_SERVO, SoundSource.NEUTRAL, 8f, 1f);
            ctx.dangerAllHumans(0.55f, cycle.allowanceTicks + 6, Math.max(1, cycle.allowanceTicks / 7), 0xFFD02020);
        } else if (cycleTick == cycle.chantTicks + cycle.allowanceTicks) {
            // eyes light up: from now on any movement is fatal
            setLight(ctx, DollCycle.Light.RED);
            doll.setEyes(true);
            doll.setState(DollEntity.State.FACING_PLAYERS);
            doll.setScanning(true);
            ctx.soundAt(dollPos.add(0, 6, 0), ModSounds.DOLL_EYES_ON, SoundSource.NEUTRAL, 8f, 1f);
            for (Contestant c : ctx.alive()) {
                Track t = tracks.get(c.number);
                LivingEntity b = c.body(ctx.level);
                if (t != null && b != null) {
                    t.airborneAtWatch = !b.onGround();
                    t.last = b.position();
                }
            }
            ctx.dangerAllHumans(0.22f, cycle.watchedTicks, 0, 0xFFC01010);
        } else if (cycleTick >= cycle.totalTicks()) {
            // red light over: eyes off, the doll turns back to the tree and the next chant begins immediately
            doll.setEyes(false);
            doll.setScanning(false);
            doll.setState(DollEntity.State.TURNING_TO_TREE);
            ctx.soundAt(dollPos.add(0, 6, 0), ModSounds.DOLL_EYES_OFF, SoundSource.NEUTRAL, 6f, 1f);
            double progress = progressOf(ctx);
            newCycle(ctx, progress);
            setLight(ctx, DollCycle.Light.GREEN);
            // keep the chant sound/animation in sync: the first syllable plays on this very tick
            cycleTick = 0;
        }
    }

    private void logProgress(GameContext ctx) {
        if (!com.squidgame.SquidConfig.get().debug) {
            return;
        }
        double sum = 0;
        int n = 0;
        double best = -1e9;
        for (Contestant c : ctx.alive()) {
            LivingEntity b = c.body(ctx.level);
            Track t = tracks.get(c.number);
            if (b != null && t != null && !t.finished) {
                sum += b.getZ();
                best = Math.max(best, b.getZ());
                n++;
            }
        }
        com.squidgame.SquidGameMod.debug("RLGL cycle {}: {} on the field, average z {}, front z {}, finished {}", cycleIndex, n,
                n == 0 ? "-" : String.format("%.1f", sum / n), String.format("%.1f", best), finishCounter);
    }

    private void newCycle(GameContext ctx, double progress) {
        logProgress(ctx);
        cycle = DollCycle.generate(cycleRng, difficulty, progress);
        cycleTick = 0;
        cycleIndex++;
        syllablesSung = 0;
        cycleStartTick = ctx.now();
        setLight(ctx, DollCycle.Light.GREEN);
    }

    private void setLight(GameContext ctx, DollCycle.Light l) {
        if (light != l) {
            light = l;
            lightChangedTick = ctx.now();
        }
    }

    /** Fraction of the field the average live contestant has covered (drives how nasty later cycles get). */
    private double progressOf(GameContext ctx) {
        double sum = 0;
        int n = 0;
        for (Contestant c : ctx.alive()) {
            Vec3 p = c.position(ctx.level);
            if (p != null) {
                sum += Mth.clamp((p.z - startZ) / Math.max(1.0, finishZ - startZ), 0, 1);
                n++;
            }
        }
        return n == 0 ? 0 : sum / n;
    }

    // ------------------------------------------------------------------ end of game

    @Override
    public boolean isFinished(GameContext ctx) {
        for (Contestant c : ctx.alive()) {
            Track t = tracks.get(c.number);
            if (t == null || !t.finished) {
                return false;
            }
        }
        return started;
    }

    @Override
    public void onTimeout(GameContext ctx) {
        ctx.title(Component.translatable("squidgame.game.red_light.time_up"), Component.empty(), 0, 30, 10);
    }

    @Override
    public GameResult conclude(GameContext ctx) {
        List<Contestant> out = new ArrayList<>();
        int i = 0;
        for (Contestant c : new ArrayList<>(ctx.alive())) {
            Track t = tracks.get(c.number);
            if (t == null || !t.finished) {
                // the guards deal with everyone who did not make it, one after another
                ctx.schedule(Math.min(90, i * 3), () -> ctx.eliminateByGuard(c, 6));
                out.add(c);
                i++;
            }
        }
        List<Contestant> survivors = new ArrayList<>();
        for (Contestant c : ctx.alive()) {
            Track t = tracks.get(c.number);
            if (t != null && t.finished) {
                survivors.add(c);
            }
        }
        com.squidgame.SquidGameMod.debug("RLGL concluded: {} crossed the line, {} did not cross in time ({} cycles)", survivors.size(), out.size(), cycleIndex);
        if (doll != null) {
            doll.setEyes(false);
            doll.setScanning(false);
            if (doll.state() == DollEntity.State.FACING_PLAYERS) {
                doll.setTurnTicks(20);
                doll.setState(DollEntity.State.TURNING_TO_TREE);
            } else if (doll.state() != DollEntity.State.TURNING_TO_TREE) {
                doll.setState(DollEntity.State.FACING_TREE);
            }
        }
        return new GameResult(survivors, out, Component.translatable("squidgame.game.red_light.headline", survivors.size()),
                Component.translatable("squidgame.game.red_light.detail", finishCounter));
    }

    @Override
    public void cleanup(GameContext ctx) {
        started = false;
        if (doll != null) {
            doll.discard();
            doll = null;
        }
        ctx.cleanupGuards();
        tracks.clear();
    }

    @Override
    public void hudWidgets(GameContext ctx, @Nullable Contestant viewer, List<HudPayload.Widget> out) {
        if (!started) {
            return;
        }
        boolean safe = viewer != null && tracks.get(viewer.number) != null && tracks.get(viewer.number).finished;
        int state = switch (light) {
            case GREEN -> 0;
            case TURNING -> 1;
            case RED -> 2;
        };
        Component label = switch (light) {
            case GREEN -> Component.translatable("squidgame.game.red_light.light.green");
            case TURNING -> Component.translatable("squidgame.game.red_light.light.turning");
            case RED -> Component.translatable("squidgame.game.red_light.light.red");
        };
        if (!safe) {
            out.add(HudPayload.Widget.light("light", label, state));
            // the big "freeze / stop" banners are instructions for those still playing (an eliminated viewer sees the
            // elimination caption in the same spot, spectators only get the light)
            boolean playing = viewer != null && viewer.isAlive();
            if (playing && light == DollCycle.Light.RED) {
                out.add(HudPayload.Widget.banner("freeze", Component.translatable("squidgame.game.red_light.banner.freeze"), 0xFF3030));
            } else if (playing && light == DollCycle.Light.TURNING) {
                out.add(HudPayload.Widget.banner("stop", Component.translatable("squidgame.game.red_light.banner.stop"), 0xFFC030));
            }
        }
        if (viewer != null && viewer.isAlive()) {
            Vec3 p = viewer.position(ctx.level);
            if (p != null && !safe) {
                int metres = (int) Math.max(0, finishZ - p.z);
                out.add(HudPayload.Widget.counter("distance", "icon_rope", Component.translatable("squidgame.game.red_light.hud.distance"), metres, -1));
            }
        }
        out.add(HudPayload.Widget.line("finished", Component.translatable("squidgame.game.red_light.hud.finished", finishCounter)));
    }

    // ------------------------------------------------------------------ helpers for NPC behaviour

    /** True once the contestant crossed the finish line. */
    public boolean hasFinished(int number) {
        Track t = tracks.get(number);
        return t != null && t.finished;
    }

    public boolean isCondemned(int number) {
        Track t = tracks.get(number);
        return t != null && t.condemned;
    }
}
