package net.palemeridian.test;

import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;
import net.fabricmc.fabric.api.gametest.v1.GameTest;
import net.minecraft.core.BlockPos;
import net.minecraft.gametest.framework.GameTestAssertException;
import net.minecraft.gametest.framework.GameTestHelper;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.Identifier;
import net.minecraft.server.MinecraftServer;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.entity.EntityTypes;
import net.minecraft.world.scores.Objective;
import net.minecraft.world.scores.ReadOnlyScoreInfo;
import net.minecraft.world.scores.ScoreHolder;

/**
 * Runtime tests for the Pale Meridian campaign. They start Minecraft's headless game-test server, so
 * they only run when the operator opts in (and thereby accepts the Minecraft EULA themselves):
 * {@code ./gradlew runGameTest -Ppm_accept_eula=true}. The fixture is generated by tools/gen_all.py.
 */
public class CampaignGameTests {
	private static JsonObject fixture() {
		try (InputStream in = CampaignGameTests.class.getResourceAsStream("/palemeridian-tests/fixture.json")) {
			return JsonParser.parseReader(new InputStreamReader(in, StandardCharsets.UTF_8)).getAsJsonObject();
		} catch (Exception e) {
			throw new IllegalStateException("missing game-test fixture", e);
		}
	}

	private static int score(MinecraftServer server, String holder, String objective) {
		Objective obj = server.getScoreboard().getObjective(objective);
		if (obj == null) {
			return Integer.MIN_VALUE;
		}
		ReadOnlyScoreInfo info = server.getScoreboard().getPlayerScoreInfo(ScoreHolder.forNameOnly(holder), obj);
		return info == null ? Integer.MIN_VALUE : info.value();
	}

	private static int quest(MinecraftServer server, String id) {
		return score(server, id, "pm.q");
	}

	private static void run(MinecraftServer server, String command) {
		server.getCommands().performPrefixedCommand(server.createCommandSourceStack().withSuppressedOutput(), command);
	}

	private static void check(GameTestHelper helper, boolean condition, String message) {
		if (!condition) {
			throw new GameTestAssertException(Component.literal(message), (int) helper.getTick());
		}
	}

	/**
	 * Walks the whole main quest line: activation order, idempotent completion, the Landing lamp
	 * blueprint, the bell puzzle (wrong order resets, right order solves), the restoration request
	 * hand-off to the Java service, then an ending and the epilogue.
	 */
	@GameTest(maxTicks = 900)
	public void campaignStateMachine(GameTestHelper helper) {
		MinecraftServer server = helper.getLevel().getServer();
		JsonObject fx = fixture();
		for (JsonElement f : fx.getAsJsonArray("functions")) {
			check(helper, server.getFunctions().get(Identifier.parse(f.getAsString())).isPresent(), "function missing: " + f.getAsString());
		}
		run(server, "function palemeridian:core/load");
		run(server, "execute unless score #init pm.world matches 1 run function palemeridian:core/world_init");
		check(helper, quest(server, "p.letter") == 1, "p.letter should be active at the start, was " + quest(server, "p.letter"));

		// completion is idempotent: completing twice advances the story once
		int rev = score(server, "#rev", "pm.world");
		run(server, "function palemeridian:q/p.letter/complete");
		run(server, "function palemeridian:q/p.letter/complete");
		check(helper, quest(server, "p.letter") == 2, "p.letter not completed");
		check(helper, score(server, "#rev", "pm.world") == rev + 1, "completing twice must count once");
		check(helper, quest(server, "p.camp") == 1, "p.camp should activate after p.letter");

		// the Landing lamp blueprint recognises the placed parts
		run(server, "function palemeridian:admin/force {q:\"p.camp\"}");
		check(helper, quest(server, "p.lamp") == 1, "p.lamp should be active");
		JsonArray parts = fx.getAsJsonArray("landing_lamp");
		JsonArray first = parts.get(0).getAsJsonObject().getAsJsonArray("pos");
		run(server, "forceload add " + first.get(0).getAsInt() + " " + first.get(2).getAsInt());
		for (JsonElement p : parts) {
			JsonArray pos = p.getAsJsonObject().getAsJsonArray("pos");
			run(server, "setblock " + pos.get(0).getAsInt() + " " + pos.get(1).getAsInt() + " " + pos.get(2).getAsInt() + " minecraft:" + p.getAsJsonObject().get("block").getAsString());
		}
		run(server, "function palemeridian:bp/landing_lamp/check");
		check(helper, quest(server, "p.lamp") == 2, "blueprint did not complete p.lamp");
		check(helper, score(server, "#r.landing", "pm.world") == 1, "Landing not marked restored");

		helper.runAfterDelay(5, () -> {
			check(helper, score(server, "#req.landing", "pm.world") == 0, "restoration request was not picked up by the Java service");

			// the bell puzzle: a wrong bell resets, the right order solves it
			List<String> order = new ArrayList<>();
			for (JsonElement e : fx.getAsJsonArray("main_order")) {
				order.add(e.getAsString());
			}
			for (String q : List.of("p.road", "c1.odile", "c1.names")) {
				run(server, "function palemeridian:admin/force {q:\"" + q + "\"}");
			}
			check(helper, quest(server, "c1.round") == 1, "c1.round should be active");
			run(server, "function palemeridian:c1/bell {n:2}");
			check(helper, score(server, "#round.step", "pm.world") <= 0, "a wrong first bell must reset the Round");
			for (int n = 1; n <= 4; n++) {
				run(server, "function palemeridian:c1/bell {n:" + n + "}");
			}
			check(helper, quest(server, "c1.round") == 2, "ringing the bells in order must solve the Round");

			// the rest of the main line, one step at a time: each completion activates the next step
			int start = order.indexOf("c1.lamp");
			int chart = order.indexOf("c4.chart");
			for (int i = start; i < chart; i++) {
				String q = order.get(i);
				check(helper, quest(server, q) == 1, q + " should be active before it is completed, was " + quest(server, q));
				run(server, "function palemeridian:admin/force {q:\"" + q + "\"}");
				check(helper, quest(server, q) == 2, q + " did not complete");
			}
			check(helper, quest(server, "c4.chart") == 1, "the final choice should be open");
			run(server, "function palemeridian:c4/ending/true");
			check(helper, score(server, "#ending", "pm.world") == 1, "the ending was not recorded");
			run(server, "function palemeridian:c4/ending/blank");
			check(helper, score(server, "#ending", "pm.world") == 1, "a second ending must be refused");
		});
		// c4/ending/after completes the choice 10 s later; the epilogue follows immediately
		helper.succeedWhen(() -> {
			check(helper, quest(server, "c4.chart") == 2, "waiting for the choice to complete");
			check(helper, quest(server, "ep.complete") == 2, "epilogue not reached");
			check(helper, score(server, "#r.deepcut", "pm.world") == 1, "the TRUE ending must restore the Deepcut");
		});
	}

	/** NPCs have fixed identities: spawning twice never makes a second body or click target. */
	@GameTest(maxTicks = 40)
	public void npcSpawnIsUnique(GameTestHelper helper) {
		MinecraftServer server = helper.getLevel().getServer();
		ServerPlayer player = helper.makeMockServerPlayerInLevel();
		BlockPos at = helper.absolutePos(new BlockPos(1, 1, 1));
		player.teleportTo(at.getX() + 0.5, at.getY(), at.getZ() + 2.5);
		String args = "{x:" + (at.getX() + 0.5) + "d,y:" + at.getY() + ".0d,z:" + (at.getZ() + 0.5) + "d,yaw:0.0f,bx:" + at.getX() + ",by:" + at.getY() + ",bz:" + at.getZ() + "}";
		run(server, "function palemeridian:npc/mirelle/spawn_at " + args);
		run(server, "function palemeridian:npc/mirelle/spawn_at " + args);
		helper.runAfterDelay(2, () -> {
			int bodies = helper.getLevel().getEntities(EntityTypes.MANNEQUIN, e -> e.entityTags().contains("pm.npc.mirelle")).size();
			int targets = helper.getLevel().getEntities(EntityTypes.INTERACTION, e -> e.entityTags().contains("pm.int.mirelle")).size();
			run(server, "function palemeridian:npc/mirelle/despawn");
			check(helper, bodies == 1, "expected one body, found " + bodies);
			check(helper, targets == 1, "expected one click target, found " + targets);
			helper.succeed();
		});
	}

	/** Picking up a keepsake records its name for the whole world, once. */
	@GameTest(maxTicks = 40)
	public void keepsakeIsRecorded(GameTestHelper helper) {
		MinecraftServer server = helper.getLevel().getServer();
		ServerPlayer player = helper.makeMockServerPlayerInLevel();
		int before = score(server, "#k.count", "pm.world");
		run(server, "give " + player.getScoreboardName() + " minecraft:paper[minecraft:custom_data={pm:{keepsake:8}}] 1");
		run(server, "give " + player.getScoreboardName() + " minecraft:paper[minecraft:custom_data={pm:{keepsake:8}}] 1");
		helper.succeedWhen(() -> {
			check(helper, score(server, "#k.8", "pm.world") == 1, "keepsake 8 not recorded");
			check(helper, score(server, "#k.count", "pm.world") == Math.max(0, before) + 1, "a keepsake must count once");
		});
	}
}
