org.gradle.jvmargs=-Xmx4G
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configureondemand=true

org.gradle.configuration-cache=true
org.gradle.configuration-cache.parallel=true
org.gradle.configuration-cache.problems=warn

net.minecraftforge.gradle.merge-source-sets=true

# ---- Mod properties ----
mod_id=terracraft
mod_name=TerraCraft
mod_version=0.1.0
mod_group=com.terracraft
mod_authors=TerraCraft Team
minecraft_version=26.2
minecraft_version_range=[26.2,26.3)
forge_version=65.1.0
forge_version_range=[65,)
loader_version_range=[65,)
