package com.starforged.moon.client;

import com.starforged.client.model.ModLayers;
import com.starforged.moon.boss.PaleMatriarchEntity;
import com.starforged.moon.client.MoonRenderStates.AnchorState;
import com.starforged.moon.client.MoonRenderStates.KitState;
import com.starforged.moon.client.MoonRenderStates.LeaperState;
import com.starforged.moon.client.MoonRenderStates.LurkerState;
import com.starforged.moon.client.MoonRenderStates.MatriarchState;
import com.starforged.moon.client.MoonRenderStates.SentinelState;
import com.starforged.moon.client.MoonRenderStates.SkimmerState;
import com.starforged.client.render.StarforgedRenderStates.CreatureState;
import net.minecraft.client.model.EntityModel;
import net.minecraft.client.model.Model;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.renderer.rendertype.RenderTypes;
import net.minecraft.util.Mth;

/** Animated models for the Moonforged creatures (geometry in ModelGeometry, generated by tools/gen_models.py). */
public final class MoonModels {
    private static final float DEG = Mth.DEG_TO_RAD;

    private MoonModels() {
    }

    // --- Regolith Skimmer --------------------------------------------------------------------------------------

    public static class RegolithSkimmerModel extends EntityModel<SkimmerState> {
        private final ModelPart body;
        private final ModelPart jaw;
        private final ModelPart rightFin;
        private final ModelPart leftFin;
        private final ModelPart tail1;
        private final ModelPart tail2;
        private final ModelPart dorsal;

        public RegolithSkimmerModel(ModelPart root) {
            super(root);
            this.body = root.getChild("body");
            this.jaw = ModLayers.path(root, "body/head/jaw");
            this.rightFin = this.body.getChild("right_fin");
            this.leftFin = this.body.getChild("left_fin");
            this.tail1 = this.body.getChild("tail1");
            this.tail2 = this.tail1.getChild("tail2");
            this.dorsal = root.getChild("dorsal");
        }

        @Override
        public void setupAnim(SkimmerState state) {
            super.setupAnim(state);
            float age = state.ageInTicks;
            float swim = state.walkAnimationPos;
            float speed = Math.min(1.0F, state.walkAnimationSpeed * 1.5F);
            this.body.visible = state.emerge > 0.05F;
            float sway = Mth.sin(swim * 0.7F) * 0.35F * speed + Mth.sin(age * 0.1F) * 0.08F;
            this.body.yRot = sway * 0.3F;
            this.tail1.yRot = -sway;
            this.tail2.yRot = -sway * 1.4F;
            float flap = Mth.sin(age * 0.3F) * 0.25F;
            this.rightFin.zRot = flap;
            this.leftFin.zRot = -flap;
            this.dorsal.zRot = sway * 0.4F;
            this.jaw.xRot = state.emerge > 0.5F ? 0.5F + Mth.sin(age * 0.6F) * 0.3F : 0.05F;
            this.body.xRot = -state.emerge * 0.35F;
        }
    }

    // --- Lunar Moth --------------------------------------------------------------------------------------------

    public static class LunarMothModel extends EntityModel<CreatureState> {
        private final ModelPart body;
        private final ModelPart rightWing;
        private final ModelPart leftWing;
        private final ModelPart rightHind;
        private final ModelPart leftHind;

        public LunarMothModel(ModelPart root) {
            super(root);
            this.body = root.getChild("body");
            this.rightWing = this.body.getChild("right_wing");
            this.leftWing = this.body.getChild("left_wing");
            this.rightHind = this.body.getChild("right_hind_wing");
            this.leftHind = this.body.getChild("left_hind_wing");
        }

        @Override
        public void setupAnim(CreatureState state) {
            super.setupAnim(state);
            float age = state.ageInTicks;
            float flap = Mth.sin(age * 0.9F) * 0.9F;
            this.rightWing.zRot = flap;
            this.leftWing.zRot = -flap;
            this.rightHind.zRot = flap * 0.8F;
            this.leftHind.zRot = -flap * 0.8F;
            this.body.y += Mth.sin(age * 0.2F) * 1.2F;
            this.body.xRot = 0.15F;
        }
    }

    // --- Selenite Sentinel -------------------------------------------------------------------------------------

    public static class SeleniteSentinelModel extends EntityModel<SentinelState> {
        private final ModelPart head;
        private final ModelPart rightArm;
        private final ModelPart leftArm;
        private final ModelPart rightLeg;
        private final ModelPart leftLeg;

        public SeleniteSentinelModel(ModelPart root) {
            super(root);
            this.head = root.getChild("head");
            this.rightArm = root.getChild("right_arm");
            this.leftArm = root.getChild("left_arm");
            this.rightLeg = root.getChild("right_leg");
            this.leftLeg = root.getChild("left_leg");
        }

        @Override
        public void setupAnim(SentinelState state) {
            super.setupAnim(state);
            float pos = state.walkAnimationPos;
            float speed = Math.min(1.0F, state.walkAnimationSpeed);
            this.head.yRot = state.yRot * DEG;
            this.head.xRot = state.xRot * DEG;
            this.rightLeg.xRot = Mth.cos(pos * 0.6F) * 0.8F * speed;
            this.leftLeg.xRot = -Mth.cos(pos * 0.6F) * 0.8F * speed;
            this.rightArm.xRot = -Mth.cos(pos * 0.6F) * 0.5F * speed;
            this.leftArm.xRot = Mth.cos(pos * 0.6F) * 0.5F * speed;
            if (state.charge > 0) {
                float c = Math.min(1.0F, state.charge / 20.0F);
                this.rightArm.xRot = -2.4F * c;
                this.leftArm.xRot = -2.4F * c;
                this.rightArm.zRot = 0.3F * c;
                this.leftArm.zRot = -0.3F * c;
            }
            if (state.attackTime > 0.0F) {
                float swing = Mth.sin(state.attackTime * Mth.PI);
                this.rightArm.xRot = -2.0F + swing * 2.4F;
                this.leftArm.xRot = -2.0F + swing * 2.4F;
            }
        }
    }

    // --- Umbral Lurker -----------------------------------------------------------------------------------------

    public static class UmbralLurkerModel extends EntityModel<LurkerState> {
        private final ModelPart head;
        private final ModelPart rightArm;
        private final ModelPart leftArm;
        private final ModelPart rightLeg;
        private final ModelPart leftLeg;

        public UmbralLurkerModel(ModelPart root) {
            super(root);
            this.head = root.getChild("head");
            this.rightArm = root.getChild("right_arm");
            this.leftArm = root.getChild("left_arm");
            this.rightLeg = root.getChild("right_leg");
            this.leftLeg = root.getChild("left_leg");
        }

        @Override
        public void setupAnim(LurkerState state) {
            super.setupAnim(state);
            float pos = state.watched ? state.frozenWalk : state.walkAnimationPos;
            float speed = Math.min(1.0F, state.walkAnimationSpeed * 1.4F);
            this.head.yRot = state.yRot * DEG;
            this.head.xRot = state.xRot * DEG;
            this.head.zRot = state.watched ? 0.25F : 0.0F;
            this.rightLeg.xRot = Mth.cos(pos * 0.8F) * 1.1F * speed;
            this.leftLeg.xRot = -Mth.cos(pos * 0.8F) * 1.1F * speed;
            this.rightArm.xRot = -0.3F - Mth.cos(pos * 0.8F) * 0.8F * speed;
            this.leftArm.xRot = -0.3F + Mth.cos(pos * 0.8F) * 0.8F * speed;
            this.rightArm.zRot = 0.08F;
            this.leftArm.zRot = -0.08F;
            if (state.attackTime > 0.0F) {
                float swing = Mth.sin(state.attackTime * Mth.PI);
                this.rightArm.xRot = -1.8F * swing;
                this.leftArm.xRot = -1.8F * swing;
            }
        }
    }

    // --- Moonkit -----------------------------------------------------------------------------------------------

    public static class MoonkitModel extends EntityModel<KitState> {
        private final ModelPart body;
        private final ModelPart head;
        private final ModelPart tail;
        private final ModelPart[] legs = new ModelPart[4];

        public MoonkitModel(ModelPart root) {
            super(root);
            this.body = root.getChild("body");
            this.head = root.getChild("head");
            this.tail = root.getChild("tail");
            this.legs[0] = root.getChild("right_front_leg");
            this.legs[1] = root.getChild("left_front_leg");
            this.legs[2] = root.getChild("right_hind_leg");
            this.legs[3] = root.getChild("left_hind_leg");
        }

        @Override
        public void setupAnim(KitState state) {
            super.setupAnim(state);
            float pos = state.walkAnimationPos;
            float speed = Math.min(1.0F, state.walkAnimationSpeed * 1.5F);
            this.head.yRot = state.yRot * DEG;
            this.head.xRot = state.xRot * DEG;
            for (int i = 0; i < 4; i++) {
                float phase = (i == 0 || i == 3) ? 0.0F : Mth.PI;
                this.legs[i].xRot = Mth.cos(pos * 1.2F + phase) * 1.0F * speed;
            }
            this.tail.yRot = Mth.sin(state.ageInTicks * 0.2F) * 0.4F;
            if (state.sitting) {
                this.body.y += 2.0F;
                this.head.y += 2.0F;
                this.tail.y += 3.0F;
                this.tail.xRot = 1.2F;
                this.legs[2].xRot = -1.4F;
                this.legs[3].xRot = -1.4F;
                this.legs[2].y += 2.5F;
                this.legs[3].y += 2.5F;
            }
        }
    }

    // --- Moonleaper --------------------------------------------------------------------------------------------

    public static class MoonleaperModel extends EntityModel<LeaperState> {
        private final ModelPart body;
        private final ModelPart head;
        private final ModelPart rightEar;
        private final ModelPart leftEar;
        private final ModelPart rightHind;
        private final ModelPart leftHind;
        private final ModelPart rightFront;
        private final ModelPart leftFront;

        public MoonleaperModel(ModelPart root) {
            super(root);
            this.body = root.getChild("body");
            this.head = root.getChild("head");
            this.rightEar = this.head.getChild("right_ear");
            this.leftEar = this.head.getChild("left_ear");
            this.rightHind = root.getChild("right_hind_leg");
            this.leftHind = root.getChild("left_hind_leg");
            this.rightFront = root.getChild("right_front_leg");
            this.leftFront = root.getChild("left_front_leg");
        }

        @Override
        public void setupAnim(LeaperState state) {
            super.setupAnim(state);
            float pos = state.walkAnimationPos;
            float speed = Math.min(1.0F, state.walkAnimationSpeed * 1.4F);
            this.head.yRot = state.yRot * DEG * 0.6F;
            this.head.xRot = state.xRot * DEG * 0.5F;
            float hop = Mth.sin(pos * 0.9F) * speed;
            this.rightHind.xRot = hop * 0.9F;
            this.leftHind.xRot = hop * 0.9F;
            this.rightFront.xRot = -hop * 0.8F;
            this.leftFront.xRot = -hop * 0.8F;
            float earSway = Mth.sin(state.ageInTicks * 0.1F) * 0.1F;
            this.rightEar.xRot = 0.26F + earSway;
            this.leftEar.xRot = 0.26F - earSway;
            if (state.charge > 0) {
                float c = state.charge / 30.0F;
                this.body.y += 3.0F * c;
                this.head.y += 3.0F * c;
                this.rightHind.xRot = 0.6F * c;
                this.leftHind.xRot = 0.6F * c;
                this.rightEar.xRot = 0.26F + 0.9F * c;
                this.leftEar.xRot = 0.26F + 0.9F * c;
            }
            if (state.airborne) {
                this.rightHind.xRot = 1.2F;
                this.leftHind.xRot = 1.2F;
                this.rightFront.xRot = -1.0F;
                this.leftFront.xRot = -1.0F;
                this.rightEar.xRot = 1.1F;
                this.leftEar.xRot = 1.1F;
                this.body.xRot = -0.21F - state.lean * 0.4F;
            }
        }
    }

    // --- The Pale Matriarch ------------------------------------------------------------------------------------

    public static class PaleMatriarchModel extends EntityModel<MatriarchState> {
        private final ModelPart skirt;
        private final ModelPart torso;
        private final ModelPart head;
        private final ModelPart rightArm;
        private final ModelPart leftArm;
        private final ModelPart halo;
        private final ModelPart veil;

        public PaleMatriarchModel(ModelPart root) {
            super(root);
            this.skirt = root.getChild("skirt");
            this.torso = this.skirt.getChild("torso");
            this.head = this.torso.getChild("head");
            this.rightArm = this.torso.getChild("right_arm");
            this.leftArm = this.torso.getChild("left_arm");
            this.halo = this.torso.getChild("halo");
            this.veil = this.torso.getChild("veil");
        }

        @Override
        public void setupAnim(MatriarchState state) {
            super.setupAnim(state);
            float age = state.ageInTicks;
            float t = state.attackTicks;
            this.skirt.y += Mth.sin(age * 0.07F) * 1.2F;
            this.skirt.xRot = Mth.sin(age * 0.05F) * 0.05F;
            this.head.yRot = state.yRot * DEG * 0.5F;
            this.head.xRot = state.xRot * DEG * 0.5F;
            this.halo.zRot = age * 0.02F;
            this.veil.xRot = 0.14F + Mth.sin(age * 0.09F) * 0.06F;
            this.rightArm.xRot = Mth.sin(age * 0.06F) * 0.15F;
            this.leftArm.xRot = -Mth.sin(age * 0.06F) * 0.15F;
            this.rightArm.zRot = 0.17F + Mth.sin(age * 0.04F) * 0.05F;
            this.leftArm.zRot = -0.17F - Mth.sin(age * 0.04F) * 0.05F;
            switch (state.attack) {
                case PaleMatriarchEntity.ATTACK_LANCE -> {
                    this.rightArm.xRot = -1.6F;
                    this.leftArm.xRot = -1.6F;
                    this.rightArm.zRot = 0.4F;
                    this.leftArm.zRot = -0.4F;
                }
                case PaleMatriarchEntity.ATTACK_WAVE -> {
                    float up = Math.min(1.0F, t / 12.0F);
                    this.rightArm.zRot = 0.17F + 2.2F * up;
                    this.leftArm.zRot = -0.17F - 2.2F * up;
                }
                case PaleMatriarchEntity.ATTACK_VOLLEY -> {
                    this.rightArm.zRot = 1.2F + Mth.sin(t * 0.4F) * 0.3F;
                    this.leftArm.zRot = -1.2F - Mth.sin(t * 0.4F) * 0.3F;
                }
                case PaleMatriarchEntity.ATTACK_CRESCENT -> {
                    float swing = t < 12 ? -t / 12.0F * 2.0F : -2.0F + Math.min(1.0F, (t - 12) / 4.0F) * 3.0F;
                    this.rightArm.xRot = swing;
                }
                case PaleMatriarchEntity.ATTACK_DIVE -> {
                    this.rightArm.xRot = -2.8F;
                    this.leftArm.xRot = -2.8F;
                    this.torso.xRot = 0.4F;
                }
                default -> {
                }
            }
            if (state.phase == PaleMatriarchEntity.PHASE_INVERSION) {
                this.rightArm.zRot = 2.6F;
                this.leftArm.zRot = -2.6F;
                this.halo.zRot = age * 0.1F;
            } else if (state.phase == PaleMatriarchEntity.PHASE_STUNNED) {
                this.torso.xRot = 0.6F;
                this.head.xRot = 0.5F;
                this.rightArm.xRot = 0.6F;
                this.leftArm.xRot = 0.6F;
            }
        }
    }

    // --- Lunar Anchor ------------------------------------------------------------------------------------------

    public static class LunarAnchorModel extends Model<AnchorState> {
        private final ModelPart top;

        public LunarAnchorModel(ModelPart root) {
            super(root, RenderTypes::entityCutout);
            this.top = root.getChild("top");
        }

        @Override
        public void setupAnim(AnchorState state) {
            super.setupAnim(state);
            float age = state.ageInTicks;
            this.top.yRot = -age * 0.06F;
            this.top.y += Mth.sin(age * 0.1F) * 1.4F;
        }
    }
}
