package com.starforged.client.model;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeDeformation;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraftforge.api.distmarker.Dist;
import net.minecraftforge.api.distmarker.OnlyIn;

/**
 * GENERATED by tools/gen_models.py - do not edit by hand. Geometry for every Starforged creature;
 * the matching textures are painted by the same script so UVs always line up.
 */
@OnlyIn(Dist.CLIENT)
@SuppressWarnings("unused")
public final class ModelGeometry {
    private ModelGeometry() {
    }

    public static LayerDefinition starMite() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p0_head = root.addOrReplaceChild("head", CubeListBuilder.create().texOffs(0, 13).addBox(-2.5F, -2F, -4F, 5F, 4F, 4F), PartPose.offsetAndRotation(0F, 20.5F, -4F, 0F, 0F, 0F));
        PartDefinition p1_mandibles = p0_head.addOrReplaceChild("mandibles", CubeListBuilder.create().texOffs(22, 29).addBox(-2F, -0.5F, -2F, 4F, 1F, 2F), PartPose.offsetAndRotation(0F, 1F, -4F, 0F, 0F, 0F));
        PartDefinition p2_body = root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(32, 0).addBox(-3F, -2.5F, -4F, 6F, 5F, 6F), PartPose.offsetAndRotation(0F, 20F, 0F, 0F, 0F, 0F));
        PartDefinition p3_abdomen = root.addOrReplaceChild("abdomen", CubeListBuilder.create().texOffs(0, 0).addBox(-4F, -2.5F, 0F, 8F, 5F, 8F), PartPose.offsetAndRotation(0F, 19.5F, 2F, 0F, 0F, 0F));
        PartDefinition p4_crystal_a = p3_abdomen.addOrReplaceChild("crystal_a", CubeListBuilder.create().texOffs(18, 13).addBox(-1F, -5F, -1F, 2F, 5F, 2F), PartPose.offsetAndRotation(0F, -2F, 1F, -0.2618F, 0F, 0.1745F));
        PartDefinition p5_crystal_b = p3_abdomen.addOrReplaceChild("crystal_b", CubeListBuilder.create().texOffs(26, 13).addBox(-1F, -4F, -1F, 2F, 4F, 2F), PartPose.offsetAndRotation(-2F, -2F, 3F, 0.1745F, 0F, -0.4363F));
        PartDefinition p6_crystal_c = p3_abdomen.addOrReplaceChild("crystal_c", CubeListBuilder.create().texOffs(34, 13).addBox(-1F, -3F, -1F, 2F, 3F, 2F), PartPose.offsetAndRotation(2F, -2F, 4F, 0.3491F, 0F, 0.4363F));
        PartDefinition p7_leg_right_0 = root.addOrReplaceChild("leg_right_0", CubeListBuilder.create().texOffs(42, 13).addBox(-9F, -1F, -1F, 9F, 2F, 2F), PartPose.offsetAndRotation(-3F, 20F, -2.5F, 0F, 0F, -0.6109F));
        PartDefinition p8_leg_left_0 = root.addOrReplaceChild("leg_left_0", CubeListBuilder.create().texOffs(0, 21).addBox(0F, -1F, -1F, 9F, 2F, 2F), PartPose.offsetAndRotation(3F, 20F, -2.5F, 0F, 0F, 0.6109F));
        PartDefinition p9_leg_right_1 = root.addOrReplaceChild("leg_right_1", CubeListBuilder.create().texOffs(22, 21).addBox(-9F, -1F, -1F, 9F, 2F, 2F), PartPose.offsetAndRotation(-3F, 20F, 0.5F, 0F, 0F, -0.6109F));
        PartDefinition p10_leg_left_1 = root.addOrReplaceChild("leg_left_1", CubeListBuilder.create().texOffs(0, 25).addBox(0F, -1F, -1F, 9F, 2F, 2F), PartPose.offsetAndRotation(3F, 20F, 0.5F, 0F, 0F, 0.6109F));
        PartDefinition p11_leg_right_2 = root.addOrReplaceChild("leg_right_2", CubeListBuilder.create().texOffs(22, 25).addBox(-9F, -1F, -1F, 9F, 2F, 2F), PartPose.offsetAndRotation(-3F, 20F, 3.5F, 0F, 0F, -0.6109F));
        PartDefinition p12_leg_left_2 = root.addOrReplaceChild("leg_left_2", CubeListBuilder.create().texOffs(0, 29).addBox(0F, -1F, -1F, 9F, 2F, 2F), PartPose.offsetAndRotation(3F, 20F, 3.5F, 0F, 0F, 0.6109F));
        return LayerDefinition.create(mesh, 64, 64);
    }

    public static LayerDefinition voidStalker() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p0_head = root.addOrReplaceChild("head", CubeListBuilder.create().texOffs(28, 27).addBox(-3F, -10F, -3.5F, 6F, 10F, 7F), PartPose.offsetAndRotation(0F, -15F, 0F, 0F, 0F, 0F));
        PartDefinition p1_body = root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(0, 27).addBox(-4.5F, 0F, -2.5F, 9F, 15F, 5F), PartPose.offsetAndRotation(0F, -15F, 0F, 0F, 0F, 0F));
        PartDefinition p2_right_arm = root.addOrReplaceChild("right_arm", CubeListBuilder.create().texOffs(24, 0).addBox(-1.5F, -1.5F, -1.5F, 3F, 22F, 3F), PartPose.offsetAndRotation(-6F, -13F, 0F, 0F, 0F, 0F));
        PartDefinition p3_claw_right_0 = p2_right_arm.addOrReplaceChild("claw_right_0", CubeListBuilder.create().texOffs(54, 27).addBox(-0.5F, 0F, -0.5F, 1F, 5F, 1F), PartPose.offsetAndRotation(-1F, 21F, 0F, 0F, 0F, 0F));
        PartDefinition p4_claw_right_1 = p2_right_arm.addOrReplaceChild("claw_right_1", CubeListBuilder.create().texOffs(58, 27).addBox(-0.5F, 0F, -0.5F, 1F, 5F, 1F), PartPose.offsetAndRotation(0F, 21F, 0F, 0F, 0F, 0F));
        PartDefinition p5_claw_right_2 = p2_right_arm.addOrReplaceChild("claw_right_2", CubeListBuilder.create().texOffs(0, 47).addBox(-0.5F, 0F, -0.5F, 1F, 5F, 1F), PartPose.offsetAndRotation(1F, 21F, 0F, 0F, 0F, 0F));
        PartDefinition p6_left_arm = root.addOrReplaceChild("left_arm", CubeListBuilder.create().texOffs(36, 0).addBox(-1.5F, -1.5F, -1.5F, 3F, 22F, 3F), PartPose.offsetAndRotation(6F, -13F, 0F, 0F, 0F, 0F));
        PartDefinition p7_claw_left_0 = p6_left_arm.addOrReplaceChild("claw_left_0", CubeListBuilder.create().texOffs(4, 47).addBox(-0.5F, 0F, -0.5F, 1F, 5F, 1F), PartPose.offsetAndRotation(-1F, 21F, 0F, 0F, 0F, 0F));
        PartDefinition p8_claw_left_1 = p6_left_arm.addOrReplaceChild("claw_left_1", CubeListBuilder.create().texOffs(8, 47).addBox(-0.5F, 0F, -0.5F, 1F, 5F, 1F), PartPose.offsetAndRotation(0F, 21F, 0F, 0F, 0F, 0F));
        PartDefinition p9_claw_left_2 = p6_left_arm.addOrReplaceChild("claw_left_2", CubeListBuilder.create().texOffs(12, 47).addBox(-0.5F, 0F, -0.5F, 1F, 5F, 1F), PartPose.offsetAndRotation(1F, 21F, 0F, 0F, 0F, 0F));
        PartDefinition p10_right_leg = root.addOrReplaceChild("right_leg", CubeListBuilder.create().texOffs(0, 0).addBox(-1.5F, 0F, -1.5F, 3F, 24F, 3F), PartPose.offsetAndRotation(-2.5F, 0F, 0F, 0F, 0F, 0F));
        PartDefinition p11_left_leg = root.addOrReplaceChild("left_leg", CubeListBuilder.create().texOffs(12, 0).addBox(-1.5F, 0F, -1.5F, 3F, 24F, 3F), PartPose.offsetAndRotation(2.5F, 0F, 0F, 0F, 0F, 0F));
        return LayerDefinition.create(mesh, 64, 64);
    }

    public static LayerDefinition astralGolem() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p0_body = root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(0, 35).addBox(-10F, -10F, -6F, 20F, 16F, 12F).texOffs(36, 63).addBox(-3F, -6F, -6.6F, 6F, 6F, 1F), PartPose.offsetAndRotation(0F, -8F, 0F, 0F, 0F, 0F));
        PartDefinition p1_back_crystal_a = p0_body.addOrReplaceChild("back_crystal_a", CubeListBuilder.create().texOffs(96, 35).addBox(-2F, -9F, -2F, 4F, 9F, 4F), PartPose.offsetAndRotation(-4F, -8F, 6F, 0.6109F, 0F, -0.2618F));
        PartDefinition p2_back_crystal_b = p0_body.addOrReplaceChild("back_crystal_b", CubeListBuilder.create().texOffs(112, 35).addBox(-1.5F, -7F, -1.5F, 3F, 7F, 3F), PartPose.offsetAndRotation(3F, -6F, 6F, 0.7854F, 0F, 0.3491F));
        PartDefinition p3_back_crystal_c = p0_body.addOrReplaceChild("back_crystal_c", CubeListBuilder.create().texOffs(24, 63).addBox(-1.5F, -6F, -1.5F, 3F, 6F, 3F), PartPose.offsetAndRotation(0F, -1F, 6F, 1.0472F, 0F, 0F));
        PartDefinition p4_head = root.addOrReplaceChild("head", CubeListBuilder.create().texOffs(64, 35).addBox(-4F, -7F, -5F, 8F, 8F, 8F), PartPose.offsetAndRotation(0F, -17F, -3F, 0F, 0F, 0F));
        PartDefinition p5_right_arm = root.addOrReplaceChild("right_arm", CubeListBuilder.create().texOffs(0, 0).addBox(-6F, -2F, -3.5F, 7F, 28F, 7F), PartPose.offsetAndRotation(-12F, -15F, 0F, 0F, 0F, 0F));
        PartDefinition p6_right_shoulder_crystal = p5_right_arm.addOrReplaceChild("right_shoulder_crystal", CubeListBuilder.create().texOffs(0, 63).addBox(-1.5F, -7F, -1.5F, 3F, 7F, 3F), PartPose.offsetAndRotation(0F, -2F, 0F, 0F, 0F, -0.3491F));
        PartDefinition p7_left_arm = root.addOrReplaceChild("left_arm", CubeListBuilder.create().texOffs(28, 0).addBox(-1F, -2F, -3.5F, 7F, 28F, 7F), PartPose.offsetAndRotation(12F, -15F, 0F, 0F, 0F, 0F));
        PartDefinition p8_left_shoulder_crystal = p7_left_arm.addOrReplaceChild("left_shoulder_crystal", CubeListBuilder.create().texOffs(12, 63).addBox(-1.5F, -7F, -1.5F, 3F, 7F, 3F), PartPose.offsetAndRotation(0F, -2F, 0F, 0F, 0F, 0.3491F));
        PartDefinition p9_right_leg = root.addOrReplaceChild("right_leg", CubeListBuilder.create().texOffs(56, 0).addBox(-4F, -2F, -4F, 8F, 26F, 8F), PartPose.offsetAndRotation(-5F, 0F, 0F, 0F, 0F, 0F));
        PartDefinition p10_left_leg = root.addOrReplaceChild("left_leg", CubeListBuilder.create().texOffs(88, 0).addBox(-4F, -2F, -4F, 8F, 26F, 8F), PartPose.offsetAndRotation(5F, 0F, 0F, 0F, 0F, 0F));
        return LayerDefinition.create(mesh, 128, 128);
    }

    public static LayerDefinition mimic() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p0_base = root.addOrReplaceChild("base", CubeListBuilder.create().texOffs(0, 0).addBox(-7F, -10F, -7F, 14F, 10F, 14F).texOffs(0, 24).addBox(-6F, -10.05F, -6F, 12F, 1F, 12F).texOffs(6, 37).addBox(-5F, -12F, -6.5F, 1F, 2F, 1F).texOffs(10, 37).addBox(-2.5F, -12F, -6.5F, 1F, 2F, 1F).texOffs(14, 37).addBox(0F, -12F, -6.5F, 1F, 2F, 1F).texOffs(18, 37).addBox(2.5F, -12F, -6.5F, 1F, 2F, 1F).texOffs(22, 37).addBox(5F, -12F, -6.5F, 1F, 2F, 1F), PartPose.offsetAndRotation(0F, 24F, 0F, 0F, 0F, 0F));
        PartDefinition p1_tongue = p0_base.addOrReplaceChild("tongue", CubeListBuilder.create().texOffs(96, 24).addBox(-3F, -1.2F, -7F, 6F, 1F, 8F), PartPose.offsetAndRotation(0F, -10F, 2F, 0F, 0F, 0F));
        PartDefinition p2_lid = root.addOrReplaceChild("lid", CubeListBuilder.create().texOffs(56, 0).addBox(-7F, -5F, -14F, 14F, 5F, 14F).texOffs(48, 24).addBox(-6F, -0.05F, -13F, 12F, 0.1F, 12F).texOffs(0, 37).addBox(-1F, -2F, -15F, 2F, 4F, 1F).texOffs(26, 37).addBox(-6F, 0F, -13.5F, 1F, 2F, 1F).texOffs(30, 37).addBox(-3.5F, 0F, -13.5F, 1F, 2F, 1F).texOffs(34, 37).addBox(-1F, 0F, -13.5F, 1F, 2F, 1F).texOffs(38, 37).addBox(1.5F, 0F, -13.5F, 1F, 2F, 1F).texOffs(42, 37).addBox(4F, 0F, -13.5F, 1F, 2F, 1F).texOffs(46, 37).addBox(-6.5F, 0F, -12F, 1F, 2F, 1F).texOffs(50, 37).addBox(-6.5F, 0F, -9F, 1F, 2F, 1F).texOffs(54, 37).addBox(-6.5F, 0F, -6F, 1F, 2F, 1F).texOffs(58, 37).addBox(-6.5F, 0F, -3F, 1F, 2F, 1F).texOffs(62, 37).addBox(5.5F, 0F, -12F, 1F, 2F, 1F).texOffs(66, 37).addBox(5.5F, 0F, -9F, 1F, 2F, 1F).texOffs(70, 37).addBox(5.5F, 0F, -6F, 1F, 2F, 1F).texOffs(74, 37).addBox(5.5F, 0F, -3F, 1F, 2F, 1F), PartPose.offsetAndRotation(0F, 14F, 7F, 0F, 0F, 0F));
        return LayerDefinition.create(mesh, 128, 64);
    }

    public static LayerDefinition astralWraith() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p0_hood = root.addOrReplaceChild("hood", CubeListBuilder.create().texOffs(0, 23).addBox(-4F, -8F, -4F, 8F, 8F, 8F).texOffs(0, 53).addBox(-3F, -6.5F, -4.3F, 6F, 5F, 1F), PartPose.offsetAndRotation(0F, -2F, 0F, 0F, 0F, 0F));
        PartDefinition p1_body = root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(32, 23).addBox(-4F, 0F, -2.5F, 8F, 11F, 5F), PartPose.offsetAndRotation(0F, -2F, 0F, 0F, 0F, 0F));
        PartDefinition p2_skirt = root.addOrReplaceChild("skirt", CubeListBuilder.create().texOffs(4, 0).addBox(-5F, 0F, -3.5F, 10F, 10F, 7F), PartPose.offsetAndRotation(0F, 9F, 0F, 0F, 0F, 0F));
        PartDefinition p3_tatters = p2_skirt.addOrReplaceChild("tatters", CubeListBuilder.create().texOffs(24, 39).addBox(-5F, 0F, -3.5F, 10F, 4F, 7F), PartPose.offsetAndRotation(0F, 10F, 0F, 0F, 0F, 0F));
        PartDefinition p4_right_arm = root.addOrReplaceChild("right_arm", CubeListBuilder.create().texOffs(0, 39).addBox(-2F, -1F, -1.5F, 3F, 11F, 3F).texOffs(26, 53).addBox(-1.5F, 10F, -1F, 2F, 2F, 2F), PartPose.offsetAndRotation(-5F, 0F, 0F, 0F, 0F, 0F));
        PartDefinition p5_staff = p4_right_arm.addOrReplaceChild("staff", CubeListBuilder.create().texOffs(0, 0).addBox(-0.5F, -10F, -0.5F, 1F, 22F, 1F), PartPose.offsetAndRotation(-0.5F, 11F, -1F, -1.5708F, 0F, 0F));
        PartDefinition p6_lens = p5_staff.addOrReplaceChild("lens", CubeListBuilder.create().texOffs(14, 53).addBox(-1.5F, -3F, -1.5F, 3F, 3F, 3F), PartPose.offsetAndRotation(0F, -10F, 0F, 0F, 0F, 0F));
        PartDefinition p7_left_arm = root.addOrReplaceChild("left_arm", CubeListBuilder.create().texOffs(12, 39).addBox(-1F, -1F, -1.5F, 3F, 11F, 3F).texOffs(34, 53).addBox(-0.5F, 10F, -1F, 2F, 2F, 2F), PartPose.offsetAndRotation(5F, 0F, 0F, 0F, 0F, 0F));
        return LayerDefinition.create(mesh, 64, 64);
    }

    public static LayerDefinition starling() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p0_core = root.addOrReplaceChild("core", CubeListBuilder.create().texOffs(0, 0).addBox(-3F, -3F, -3F, 6F, 6F, 6F), PartPose.offsetAndRotation(0F, 18F, 0F, 0F, 0F, 0F));
        PartDefinition p1_point_top = p0_core.addOrReplaceChild("point_top", CubeListBuilder.create().texOffs(24, 0).addBox(-1F, -3F, -1F, 2F, 3F, 2F), PartPose.offsetAndRotation(0F, -3F, 0F, 0F, 0F, 0F));
        PartDefinition p2_point_left = p0_core.addOrReplaceChild("point_left", CubeListBuilder.create().texOffs(0, 12).addBox(-1F, -3F, -1F, 2F, 3F, 2F), PartPose.offsetAndRotation(3F, -1F, 0F, 0F, 0F, -1.2566F));
        PartDefinition p3_point_right = p0_core.addOrReplaceChild("point_right", CubeListBuilder.create().texOffs(8, 12).addBox(-1F, -3F, -1F, 2F, 3F, 2F), PartPose.offsetAndRotation(-3F, -1F, 0F, 0F, 0F, 1.2566F));
        PartDefinition p4_point_bl = p0_core.addOrReplaceChild("point_bl", CubeListBuilder.create().texOffs(16, 12).addBox(-1F, -3F, -1F, 2F, 3F, 2F), PartPose.offsetAndRotation(-2F, 3F, 0F, 0F, 0F, 2.5133F));
        PartDefinition p5_point_br = p0_core.addOrReplaceChild("point_br", CubeListBuilder.create().texOffs(24, 12).addBox(-1F, -3F, -1F, 2F, 3F, 2F), PartPose.offsetAndRotation(2F, 3F, 0F, 0F, 0F, -2.5133F));
        PartDefinition p6_right_wing = p0_core.addOrReplaceChild("right_wing", CubeListBuilder.create().texOffs(0, 17).addBox(-6F, -0.5F, 0F, 6F, 1F, 4F), PartPose.offsetAndRotation(-2F, -1F, 2.5F, 0F, 0F, 0F));
        PartDefinition p7_left_wing = p0_core.addOrReplaceChild("left_wing", CubeListBuilder.create().texOffs(0, 22).addBox(0F, -0.5F, 0F, 6F, 1F, 4F), PartPose.offsetAndRotation(2F, -1F, 2.5F, 0F, 0F, 0F));
        return LayerDefinition.create(mesh, 32, 32);
    }

    public static LayerDefinition nebulaRay() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p0_body = root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(0, 0).addBox(-8F, -2F, -10F, 16F, 4F, 20F).texOffs(0, 24).addBox(-7F, 2F, -9F, 14F, 1F, 18F), PartPose.offsetAndRotation(0F, 20F, 0F, 0F, 0F, 0F));
        PartDefinition p1_right_wing = p0_body.addOrReplaceChild("right_wing", CubeListBuilder.create().texOffs(64, 24).addBox(-14F, -1F, -8F, 14F, 2F, 16F), PartPose.offsetAndRotation(-8F, 0F, -2F, 0F, 0F, 0F));
        PartDefinition p2_right_wing_tip = p1_right_wing.addOrReplaceChild("right_wing_tip", CubeListBuilder.create().texOffs(0, 61).addBox(-12F, -0.5F, -6F, 12F, 1F, 10F), PartPose.offsetAndRotation(-14F, 0F, 0F, 0F, 0F, 0F));
        PartDefinition p3_left_wing = p0_body.addOrReplaceChild("left_wing", CubeListBuilder.create().texOffs(0, 43).addBox(0F, -1F, -8F, 14F, 2F, 16F), PartPose.offsetAndRotation(8F, 0F, -2F, 0F, 0F, 0F));
        PartDefinition p4_left_wing_tip = p3_left_wing.addOrReplaceChild("left_wing_tip", CubeListBuilder.create().texOffs(44, 61).addBox(0F, -0.5F, -6F, 12F, 1F, 10F), PartPose.offsetAndRotation(14F, 0F, 0F, 0F, 0F, 0F));
        PartDefinition p5_right_horn = p0_body.addOrReplaceChild("right_horn", CubeListBuilder.create().texOffs(112, 61).addBox(-1F, -1F, -6F, 2F, 2F, 6F), PartPose.offsetAndRotation(-5F, 0F, -10F, 0F, 0.2618F, 0F));
        PartDefinition p6_left_horn = p0_body.addOrReplaceChild("left_horn", CubeListBuilder.create().texOffs(0, 72).addBox(-1F, -1F, -6F, 2F, 2F, 6F), PartPose.offsetAndRotation(5F, 0F, -10F, 0F, -0.2618F, 0F));
        PartDefinition p7_tail1 = p0_body.addOrReplaceChild("tail1", CubeListBuilder.create().texOffs(86, 43).addBox(-1.5F, -1F, 0F, 3F, 2F, 10F), PartPose.offsetAndRotation(0F, 0F, 10F, 0F, 0F, 0F));
        PartDefinition p8_tail2 = p7_tail1.addOrReplaceChild("tail2", CubeListBuilder.create().texOffs(88, 61).addBox(-1F, -0.5F, 0F, 2F, 1F, 10F), PartPose.offsetAndRotation(0F, 0F, 10F, 0F, 0F, 0F));
        PartDefinition p9_tail3 = p8_tail2.addOrReplaceChild("tail3", CubeListBuilder.create().texOffs(60, 43).addBox(-0.5F, -0.5F, 0F, 1F, 1F, 12F), PartPose.offsetAndRotation(0F, 0F, 10F, 0F, 0F, 0F));
        return LayerDefinition.create(mesh, 128, 128);
    }

    public static LayerDefinition eclipseSovereign() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p0_body = root.addOrReplaceChild("body", CubeListBuilder.create(), PartPose.offsetAndRotation(0F, -10F, 0F, 0F, 0F, 0F));
        PartDefinition p1_waist = p0_body.addOrReplaceChild("waist", CubeListBuilder.create().texOffs(100, 0).addBox(-7F, 0F, -4.5F, 14F, 12F, 9F), PartPose.offsetAndRotation(0F, 0F, 0F, 0F, 0F, 0F));
        PartDefinition p2_trail = p1_waist.addOrReplaceChild("trail", CubeListBuilder.create().texOffs(116, 27).addBox(-5F, 0F, -3.5F, 10F, 10F, 7F), PartPose.offsetAndRotation(0F, 12F, 0F, 0F, 0F, 0F));
        PartDefinition p3_trail_tip = p2_trail.addOrReplaceChild("trail_tip", CubeListBuilder.create().texOffs(42, 47).addBox(-3F, 0F, -2F, 6F, 8F, 4F), PartPose.offsetAndRotation(0F, 10F, 0F, 0F, 0F, 0F));
        PartDefinition p4_chest = p0_body.addOrReplaceChild("chest", CubeListBuilder.create().texOffs(0, 0).addBox(-9F, -16F, -5.5F, 18F, 16F, 11F).texOffs(150, 27).addBox(-10F, -16F, -6F, 20F, 3F, 12F), PartPose.offsetAndRotation(0F, 0F, 0F, 0F, 0F, 0F));
        PartDefinition p5_core = p4_chest.addOrReplaceChild("core", CubeListBuilder.create().texOffs(150, 47).addBox(-4F, -4F, -1F, 8F, 8F, 1F), PartPose.offsetAndRotation(0F, -9F, -5.6F, 0F, 0F, 0F));
        PartDefinition p6_right_pauldron = p4_chest.addOrReplaceChild("right_pauldron", CubeListBuilder.create().texOffs(36, 27).addBox(-7F, -4F, -6F, 8F, 6F, 12F).texOffs(214, 27).addBox(-7.5F, -4.5F, -6.5F, 8F, 1F, 13F), PartPose.offsetAndRotation(-10F, -15F, 0F, 0F, 0F, 0.2094F));
        PartDefinition p7_left_pauldron = p4_chest.addOrReplaceChild("left_pauldron", CubeListBuilder.create().texOffs(76, 27).addBox(-1F, -4F, -6F, 8F, 6F, 12F).texOffs(0, 47).addBox(-0.5F, -4.5F, -6.5F, 8F, 1F, 13F), PartPose.offsetAndRotation(10F, -15F, 0F, 0F, 0F, -0.2094F));
        PartDefinition p8_head = p4_chest.addOrReplaceChild("head", CubeListBuilder.create().texOffs(146, 0).addBox(-5F, -10F, -5F, 10F, 10F, 10F).texOffs(184, 47).addBox(-4F, -8F, -5.3F, 8F, 7F, 1F), PartPose.offsetAndRotation(0F, -16F, 0F, 0F, 0F, 0F));
        PartDefinition p9_crown_0 = p8_head.addOrReplaceChild("crown_0", CubeListBuilder.create().texOffs(142, 47).addBox(-1F, -9F, -1F, 2F, 9F, 2F), PartPose.offsetAndRotation(0F, -10F, -4F, -0.1745F, 0F, 0F));
        PartDefinition p10_crown_1 = p8_head.addOrReplaceChild("crown_1", CubeListBuilder.create().texOffs(168, 47).addBox(-1F, -7F, -1F, 2F, 7F, 2F), PartPose.offsetAndRotation(-3.5F, -10F, -3F, -0.1396F, 0F, -0.3142F));
        PartDefinition p11_crown_2 = p8_head.addOrReplaceChild("crown_2", CubeListBuilder.create().texOffs(176, 47).addBox(-1F, -7F, -1F, 2F, 7F, 2F), PartPose.offsetAndRotation(3.5F, -10F, -3F, -0.1396F, 0F, 0.3142F));
        PartDefinition p12_crown_3 = p8_head.addOrReplaceChild("crown_3", CubeListBuilder.create().texOffs(16, 61).addBox(-1F, -5F, -1F, 2F, 5F, 2F), PartPose.offsetAndRotation(-5F, -10F, 1F, 0F, 0F, -0.4887F));
        PartDefinition p13_crown_4 = p8_head.addOrReplaceChild("crown_4", CubeListBuilder.create().texOffs(24, 61).addBox(-1F, -5F, -1F, 2F, 5F, 2F), PartPose.offsetAndRotation(5F, -10F, 1F, 0F, 0F, 0.4887F));
        PartDefinition p14_crown_gem = p8_head.addOrReplaceChild("crown_gem", CubeListBuilder.create().texOffs(104, 61).addBox(-1.5F, -3F, -1F, 3F, 3F, 2F), PartPose.offsetAndRotation(0F, -10F, -4.5F, 0F, 0F, 0F));
        PartDefinition p15_halo = p8_head.addOrReplaceChild("halo", CubeListBuilder.create(), PartPose.offsetAndRotation(0F, -6F, 8F, 0F, 0F, 0F));
        PartDefinition p16_halo_0 = p15_halo.addOrReplaceChild("halo_0", CubeListBuilder.create().texOffs(32, 61).addBox(-1F, -3F, -0.5F, 2F, 6F, 1F), PartPose.offsetAndRotation(11F, 0F, 0F, 0F, 0F, 0F));
        PartDefinition p17_halo_1 = p15_halo.addOrReplaceChild("halo_1", CubeListBuilder.create().texOffs(38, 61).addBox(-1F, -3F, -0.5F, 2F, 6F, 1F), PartPose.offsetAndRotation(9.5263F, 5.5F, 0F, 0F, 0F, 0.5236F));
        PartDefinition p18_halo_2 = p15_halo.addOrReplaceChild("halo_2", CubeListBuilder.create().texOffs(44, 61).addBox(-1F, -3F, -0.5F, 2F, 6F, 1F), PartPose.offsetAndRotation(5.5F, 9.5263F, 0F, 0F, 0F, 1.0472F));
        PartDefinition p19_halo_3 = p15_halo.addOrReplaceChild("halo_3", CubeListBuilder.create().texOffs(50, 61).addBox(-1F, -3F, -0.5F, 2F, 6F, 1F), PartPose.offsetAndRotation(0F, 11F, 0F, 0F, 0F, 1.5708F));
        PartDefinition p20_halo_4 = p15_halo.addOrReplaceChild("halo_4", CubeListBuilder.create().texOffs(56, 61).addBox(-1F, -3F, -0.5F, 2F, 6F, 1F), PartPose.offsetAndRotation(-5.5F, 9.5263F, 0F, 0F, 0F, 2.0944F));
        PartDefinition p21_halo_5 = p15_halo.addOrReplaceChild("halo_5", CubeListBuilder.create().texOffs(62, 61).addBox(-1F, -3F, -0.5F, 2F, 6F, 1F), PartPose.offsetAndRotation(-9.5263F, 5.5F, 0F, 0F, 0F, 2.618F));
        PartDefinition p22_halo_6 = p15_halo.addOrReplaceChild("halo_6", CubeListBuilder.create().texOffs(68, 61).addBox(-1F, -3F, -0.5F, 2F, 6F, 1F), PartPose.offsetAndRotation(-11F, 0F, 0F, 0F, 0F, 3.1416F));
        PartDefinition p23_halo_7 = p15_halo.addOrReplaceChild("halo_7", CubeListBuilder.create().texOffs(74, 61).addBox(-1F, -3F, -0.5F, 2F, 6F, 1F), PartPose.offsetAndRotation(-9.5263F, -5.5F, 0F, 0F, 0F, 3.6652F));
        PartDefinition p24_halo_8 = p15_halo.addOrReplaceChild("halo_8", CubeListBuilder.create().texOffs(80, 61).addBox(-1F, -3F, -0.5F, 2F, 6F, 1F), PartPose.offsetAndRotation(-5.5F, -9.5263F, 0F, 0F, 0F, 4.1888F));
        PartDefinition p25_halo_9 = p15_halo.addOrReplaceChild("halo_9", CubeListBuilder.create().texOffs(86, 61).addBox(-1F, -3F, -0.5F, 2F, 6F, 1F), PartPose.offsetAndRotation(0F, -11F, 0F, 0F, 0F, 4.7124F));
        PartDefinition p26_halo_10 = p15_halo.addOrReplaceChild("halo_10", CubeListBuilder.create().texOffs(92, 61).addBox(-1F, -3F, -0.5F, 2F, 6F, 1F), PartPose.offsetAndRotation(5.5F, -9.5263F, 0F, 0F, 0F, 5.236F));
        PartDefinition p27_halo_11 = p15_halo.addOrReplaceChild("halo_11", CubeListBuilder.create().texOffs(98, 61).addBox(-1F, -3F, -0.5F, 2F, 6F, 1F), PartPose.offsetAndRotation(9.5263F, -5.5F, 0F, 0F, 0F, 5.7596F));
        PartDefinition p28_cape_0 = p4_chest.addOrReplaceChild("cape_0", CubeListBuilder.create().texOffs(58, 0).addBox(-3F, 0F, 0F, 6F, 26F, 1F), PartPose.offsetAndRotation(-6F, -14F, 5F, 0F, 0F, 0F));
        PartDefinition p29_cape_1 = p4_chest.addOrReplaceChild("cape_1", CubeListBuilder.create().texOffs(72, 0).addBox(-3F, 0F, 0F, 6F, 26F, 1F), PartPose.offsetAndRotation(0F, -14F, 5F, 0F, 0F, 0F));
        PartDefinition p30_cape_2 = p4_chest.addOrReplaceChild("cape_2", CubeListBuilder.create().texOffs(86, 0).addBox(-3F, 0F, 0F, 6F, 26F, 1F), PartPose.offsetAndRotation(6F, -14F, 5F, 0F, 0F, 0F));
        PartDefinition p31_right_hand = root.addOrReplaceChild("right_hand", CubeListBuilder.create().texOffs(186, 0).addBox(-5F, -6F, -4F, 10F, 12F, 8F).texOffs(62, 47).addBox(-5.5F, -6.5F, -4.5F, 11F, 3F, 9F), PartPose.offsetAndRotation(-22F, -14F, -2F, 0F, 0F, 0F));
        PartDefinition p32_right_finger_0 = p31_right_hand.addOrReplaceChild("right_finger_0", CubeListBuilder.create().texOffs(202, 47).addBox(-1F, 0F, -1F, 2F, 6F, 2F), PartPose.offsetAndRotation(-3F, 6F, -3F, 0F, 0F, 0F));
        PartDefinition p33_right_finger_1 = p31_right_hand.addOrReplaceChild("right_finger_1", CubeListBuilder.create().texOffs(210, 47).addBox(-1F, 0F, -1F, 2F, 6F, 2F), PartPose.offsetAndRotation(-1F, 6F, -3F, 0F, 0F, 0F));
        PartDefinition p34_right_finger_2 = p31_right_hand.addOrReplaceChild("right_finger_2", CubeListBuilder.create().texOffs(218, 47).addBox(-1F, 0F, -1F, 2F, 6F, 2F), PartPose.offsetAndRotation(1F, 6F, -3F, 0F, 0F, 0F));
        PartDefinition p35_right_finger_3 = p31_right_hand.addOrReplaceChild("right_finger_3", CubeListBuilder.create().texOffs(226, 47).addBox(-1F, 0F, -1F, 2F, 6F, 2F), PartPose.offsetAndRotation(3F, 6F, -3F, 0F, 0F, 0F));
        PartDefinition p36_left_hand = root.addOrReplaceChild("left_hand", CubeListBuilder.create().texOffs(0, 27).addBox(-5F, -6F, -4F, 10F, 12F, 8F).texOffs(102, 47).addBox(-5.5F, -6.5F, -4.5F, 11F, 3F, 9F), PartPose.offsetAndRotation(22F, -14F, -2F, 0F, 0F, 0F));
        PartDefinition p37_left_finger_0 = p36_left_hand.addOrReplaceChild("left_finger_0", CubeListBuilder.create().texOffs(234, 47).addBox(-1F, 0F, -1F, 2F, 6F, 2F), PartPose.offsetAndRotation(-3F, 6F, -3F, 0F, 0F, 0F));
        PartDefinition p38_left_finger_1 = p36_left_hand.addOrReplaceChild("left_finger_1", CubeListBuilder.create().texOffs(242, 47).addBox(-1F, 0F, -1F, 2F, 6F, 2F), PartPose.offsetAndRotation(-1F, 6F, -3F, 0F, 0F, 0F));
        PartDefinition p39_left_finger_2 = p36_left_hand.addOrReplaceChild("left_finger_2", CubeListBuilder.create().texOffs(0, 61).addBox(-1F, 0F, -1F, 2F, 6F, 2F), PartPose.offsetAndRotation(1F, 6F, -3F, 0F, 0F, 0F));
        PartDefinition p40_left_finger_3 = p36_left_hand.addOrReplaceChild("left_finger_3", CubeListBuilder.create().texOffs(8, 61).addBox(-1F, 0F, -1F, 2F, 6F, 2F), PartPose.offsetAndRotation(3F, 6F, -3F, 0F, 0F, 0F));
        return LayerDefinition.create(mesh, 256, 128);
    }

    public static LayerDefinition eclipseCrystal() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p0_crystal = root.addOrReplaceChild("crystal", CubeListBuilder.create(), PartPose.offsetAndRotation(0F, 8F, 0F, 0F, 0F, 0F));
        PartDefinition p1_outer = p0_crystal.addOrReplaceChild("outer", CubeListBuilder.create().texOffs(24, 0).addBox(-5F, -5F, -5F, 10F, 10F, 10F), PartPose.offsetAndRotation(0F, 0F, 0F, 0.7854F, 0F, 0.7854F));
        PartDefinition p2_inner = p0_crystal.addOrReplaceChild("inner", CubeListBuilder.create().texOffs(0, 0).addBox(-3F, -8F, -3F, 6F, 16F, 6F), PartPose.offsetAndRotation(0F, 0F, 0F, 0F, 0.7854F, 0F));
        PartDefinition p3_heart = p0_crystal.addOrReplaceChild("heart", CubeListBuilder.create().texOffs(0, 22).addBox(-2F, -2F, -2F, 4F, 4F, 4F), PartPose.offsetAndRotation(0F, 0F, 0F, 0F, 0F, 0F));
        return LayerDefinition.create(mesh, 64, 64);
    }
}
