#version 330 compatibility
// Generated by tools/shader/build_shader.py - edit program/gbuffers_lit.glsl instead.
#define FSH
#define DIM_NETHER
#define PROGRAM_PARTICLES
#include "/program/gbuffers_lit.glsl"
