#version 330 compatibility
// Generated by tools/shader/build_shader.py - edit program/gbuffers_unlit.glsl instead.
#define FSH
#define DIM_NETHER
#define PROGRAM_BEACON
#include "/program/gbuffers_unlit.glsl"
