"""Writes docs/spoilers/QUEST_GRAPH.md from the registered quests (always in sync with the content)."""
from __future__ import annotations

from ..paths import TOOLS
from .engine import R

CHAPTERS = {0: "Prologue", 1: "Chapter 1", 2: "Chapter 2", 3: "Chapter 3", 4: "Chapter 4", 5: "Epilogue", 9: "Optional"}


def write() -> None:
    lines = [
        "# ⚠️ SPOILERS — Quest graph (generated)",
        "",
        "> Developer-only. Generated by `tools/gen_all.py` from the quest registry; do not edit by hand.",
        "> State per quest lives in scoreboard `pm.q` (0 locked, 1 active, 2 done); progress in `pm.qp`.",
        "",
        "```mermaid",
        "flowchart TD",
    ]
    for q in R.quests:
        shape = f'{q.id.replace(".", "_")}["{q.id}<br/>{q.title}"]' if q.main else f'{q.id.replace(".", "_")}(["{q.id}<br/>{q.title}"])'
        lines.append(f"  {shape}")
        for p in q.prereq:
            lines.append(f"  {p.replace('.', '_')} --> {q.id.replace('.', '_')}")
    lines += ["```", "", "| Quest | Chapter | Main | Prerequisites | Objective | Target POI | Progress |", "|---|---|---|---|---|---|---|"]
    for q in R.quests:
        lines.append(f"| `{q.id}` | {CHAPTERS.get(q.chapter, q.chapter)} | {'yes' if q.main else 'no'} | {', '.join(f'`{p}`' for p in q.prereq) or '—'} "
                     f"| {q.objective} | {f'`{q.target}`' if q.target else '—'} | {q.progress_max or '—'} |")
    lines += ["", "Auto-activation: every quest with `auto=True` activates when all its prerequisites are done "
              "(`palemeridian:q/_advance`). `ep.spoken`, `ep.kept` and `s.fen` are activated by story events instead.", ""]
    out = TOOLS.parent / "docs" / "spoilers" / "QUEST_GRAPH.md"
    out.write_text("\n".join(lines))
