"""Writes the game-test fixture (quest order, blueprint parts, puzzle data) next to the game tests."""
from __future__ import annotations

import json

from .. import poi
from ..paths import TOOLS
from .engine import R


def write() -> None:
    main = [q.id for q in R.quests if q.main and q.chapter < 5]
    lamp = poi.get("landing.lamp")["parts"]
    fixture = {
        "_comment": "Generated by tools/gen_all.py for the Pale Meridian game tests. Do not edit.",
        "functions": ["palemeridian:core/load", "palemeridian:core/tick", "palemeridian:core/second", "palemeridian:q/_advance",
                      "palemeridian:hud/refresh", "palemeridian:journal/sync", "palemeridian:admin/force", "palemeridian:c4/ending/true",
                      "palemeridian:c4/ending/blank", "palemeridian:npc/odile/spawn_at"],
        "main_order": main,
        "landing_lamp": [{"pos": p["pos"], "block": p["block"]} for p in lamp],
        "bell_order": [1, 2, 3, 4],
    }
    out = TOOLS.parent / "mod" / "src" / "gametest" / "resources" / "palemeridian-tests" / "fixture.json"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(fixture, indent=1) + "\n")
