#!/usr/bin/env python3
"""Generate the contestant model: geo json, texture, animations (+ contestant_bones.json)."""
from __future__ import annotations

import json
import sys

from common import *  # noqa: F401,F403
from lib import jsonfmt
import contestant_model as cm
import contestant_tex as ct


def write_bones_json(mb) -> None:
    geo = mb.geo
    data = {
        "_comment": "Generated by gen_contestant.py. Bone roles of geo/entity/contestant.geo.json.",
        "geometry": geo.identifier,
        "texture": "textures/entity/contestant.png",
        "texture_size": [geo.tex_w, geo.tex_h],
        "skin": cm.SKIN_BONES,
        "hair": cm.HAIR_BONES,
        "face": cm.FACE_BONES,
        "accessory": ["glasses"],
        "anchor": ["number_chest", "number_back", "item_left", "item_right"],
        "structure": ["root", "waist", "body", "head"],
        "limbs": ["left_arm", "right_arm", "left_forearm", "right_forearm", "left_leg", "right_leg",
                  "left_shin", "right_shin", "left_shoe", "right_shoe"],
        "all_bones": list(geo.bones.keys()),
    }
    jsonfmt.write(str(HERE / "contestant_bones.json"), data)


def main(with_anims: bool = True) -> None:
    ensure_dirs()
    mb = cm.build_model()
    mb.geo.write(str(GEO_DIR / "contestant.geo.json"))
    cv = ct.paint_contestant(mb)
    cv.save(str(TEX_DIR / "contestant.png"))
    write_bones_json(mb)
    if with_anims:
        try:
            import contestant_anim as ca
        except ImportError:
            print("contestant_anim not available yet - skipping animations")
        else:
            ca.build_and_write(mb)
    print(f"contestant: {len(mb.geo.bones)} bones, texture {mb.packer.used_fraction():.0%} used")


if __name__ == "__main__":
    main()
