package com.starforged.sun.client;

import com.starforged.client.model.ModLayers;
import com.starforged.sun.boss.SunWardenEntity;
import com.starforged.sun.client.SunRenderStates.HoundState;
import com.starforged.sun.client.SunRenderStates.ImpState;
import com.starforged.sun.client.SunRenderStates.KnightState;
import com.starforged.sun.client.SunRenderStates.PhoenixState;
import com.starforged.sun.client.SunRenderStates.PylonState;
import com.starforged.sun.client.SunRenderStates.WardenState;
import com.starforged.client.render.StarforgedRenderStates.CreatureState;
import com.starforged.sun.entity.AshenKnightEntity;
import net.minecraft.client.model.EntityModel;
import net.minecraft.client.model.Model;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.renderer.rendertype.RenderTypes;
import net.minecraft.util.Mth;

/** Animated models for the Sunforged creatures (geometry in ModelGeometry, generated by tools/gen_models.py). */
public final class SunModels {
    private static final float DEG = Mth.DEG_TO_RAD;

    private SunModels() {
    }

    private static float ease(float t) {
        t = Mth.clamp(t, 0.0F, 1.0F);
        return t * t * (3.0F - 2.0F * t);
    }

    // --- Cinder Imp --------------------------------------------------------------------------------------------

    public static class CinderImpModel extends EntityModel<ImpState> {
        private final ModelPart head;
        private final ModelPart body;
        private final ModelPart rightArm;
        private final ModelPart leftArm;
        private final ModelPart rightLeg;
        private final ModelPart leftLeg;
        private final ModelPart rightWing;
        private final ModelPart leftWing;
        private final ModelPart tail;

        public CinderImpModel(ModelPart root) {
            super(root);
            this.head = root.getChild("head");
            this.body = root.getChild("body");
            this.rightArm = root.getChild("right_arm");
            this.leftArm = root.getChild("left_arm");
            this.rightLeg = root.getChild("right_leg");
            this.leftLeg = root.getChild("left_leg");
            this.rightWing = root.getChild("right_wing");
            this.leftWing = root.getChild("left_wing");
            this.tail = root.getChild("tail");
        }

        @Override
        public void setupAnim(ImpState state) {
            super.setupAnim(state);
            float age = state.ageInTicks;
            float bob = Mth.sin(age * 0.25F) * 1.0F;
            for (ModelPart p : new ModelPart[]{this.head, this.body, this.rightArm, this.leftArm, this.rightLeg, this.leftLeg, this.rightWing,
                this.leftWing, this.tail}) {
                p.y += bob;
            }
            this.head.yRot = state.yRot * DEG;
            this.head.xRot = state.xRot * DEG;
            float flap = Mth.sin(age * 1.6F) * 0.7F;
            this.rightWing.yRot = 0.5F + flap;
            this.leftWing.yRot = -0.5F - flap;
            this.rightLeg.xRot = 0.3F + Mth.sin(age * 0.2F) * 0.15F;
            this.leftLeg.xRot = 0.3F + Mth.sin(age * 0.2F + 1.0F) * 0.15F;
            this.tail.xRot = 0.7F + Mth.sin(age * 0.3F) * 0.2F;
            this.tail.yRot = Mth.sin(age * 0.17F) * 0.4F;
            if (state.charging) {
                this.rightArm.xRot = -2.6F + Mth.sin(age * 0.9F) * 0.2F;
                this.leftArm.xRot = -2.6F - Mth.sin(age * 0.9F) * 0.2F;
            } else {
                this.rightArm.xRot = Mth.sin(age * 0.2F) * 0.3F;
                this.leftArm.xRot = -Mth.sin(age * 0.2F) * 0.3F;
                this.rightArm.zRot = 0.2F;
                this.leftArm.zRot = -0.2F;
            }
        }
    }

    // --- Magma Crawler -----------------------------------------------------------------------------------------

    public static class MagmaCrawlerModel extends EntityModel<CreatureState> {
        private final ModelPart body;
        private final ModelPart head;
        private final ModelPart jaw;
        private final ModelPart[] legs = new ModelPart[4];
        private final ModelPart tail1;
        private final ModelPart tail2;
        private final ModelPart tail3;

        public MagmaCrawlerModel(ModelPart root) {
            super(root);
            this.body = root.getChild("body");
            this.head = root.getChild("head");
            this.jaw = this.head.getChild("jaw");
            this.legs[0] = root.getChild("right_front_leg");
            this.legs[1] = root.getChild("left_front_leg");
            this.legs[2] = root.getChild("right_hind_leg");
            this.legs[3] = root.getChild("left_hind_leg");
            this.tail1 = root.getChild("tail1");
            this.tail2 = this.tail1.getChild("tail2");
            this.tail3 = this.tail2.getChild("tail3");
        }

        @Override
        public void setupAnim(CreatureState state) {
            super.setupAnim(state);
            float pos = state.walkAnimationPos;
            float speed = Math.min(1.0F, state.walkAnimationSpeed * 1.4F);
            float age = state.ageInTicks;
            this.head.yRot = state.yRot * DEG * 0.7F;
            this.head.xRot = state.xRot * DEG * 0.5F;
            for (int i = 0; i < 4; i++) {
                float phase = (i == 0 || i == 3) ? 0.0F : Mth.PI;
                this.legs[i].xRot = Mth.cos(pos * 0.9F + phase) * 0.9F * speed;
            }
            float sway = Mth.sin(pos * 0.9F) * 0.25F * speed + Mth.sin(age * 0.08F) * 0.1F;
            this.body.yRot = sway * 0.3F;
            this.tail1.yRot = -sway;
            this.tail2.yRot = -sway * 1.3F;
            this.tail3.yRot = -sway * 1.6F;
            float open = state.attackTime > 0.0F ? Mth.sin(state.attackTime * Mth.PI) * 0.8F : (Mth.sin(age * 0.05F) > 0.9F ? 0.25F : 0.05F);
            this.jaw.xRot = open;
        }
    }

    // --- Ember Hound -------------------------------------------------------------------------------------------

    public static class EmberHoundModel extends EntityModel<HoundState> {
        private final ModelPart body;
        private final ModelPart mane;
        private final ModelPart head;
        private final ModelPart tail;
        private final ModelPart rightFront;
        private final ModelPart leftFront;
        private final ModelPart rightHind;
        private final ModelPart leftHind;

        public EmberHoundModel(ModelPart root) {
            super(root);
            this.body = root.getChild("body");
            this.mane = root.getChild("mane");
            this.head = root.getChild("head");
            this.tail = root.getChild("tail");
            this.rightFront = root.getChild("right_front_leg");
            this.leftFront = root.getChild("left_front_leg");
            this.rightHind = root.getChild("right_hind_leg");
            this.leftHind = root.getChild("left_hind_leg");
        }

        @Override
        public void setupAnim(HoundState state) {
            super.setupAnim(state);
            float pos = state.walkAnimationPos;
            float speed = state.walkAnimationSpeed;
            float age = state.ageInTicks;
            this.head.yRot = state.yRot * DEG;
            this.head.xRot = state.xRot * DEG;
            if (state.sitting) {
                this.body.xRot = -0.45F;
                this.body.y += 2.0F;
                this.rightHind.xRot = -1.45F;
                this.leftHind.xRot = -1.45F;
                this.rightHind.y += 4.0F;
                this.leftHind.y += 4.0F;
                this.rightHind.z -= 2.0F;
                this.leftHind.z -= 2.0F;
                this.tail.xRot = 1.3F;
                this.tail.y += 4.0F;
            } else {
                this.rightFront.xRot = Mth.cos(pos * 0.6662F) * 1.4F * speed;
                this.leftFront.xRot = Mth.cos(pos * 0.6662F + Mth.PI) * 1.4F * speed;
                this.rightHind.xRot = Mth.cos(pos * 0.6662F + Mth.PI) * 1.4F * speed;
                this.leftHind.xRot = Mth.cos(pos * 0.6662F) * 1.4F * speed;
                this.tail.xRot = 0.9F + Mth.sin(age * 0.2F) * 0.1F;
            }
            this.tail.yRot = Mth.sin(age * (state.tame ? 0.6F : 0.25F)) * 0.4F;
            this.mane.y += Mth.sin(age * 0.5F) * 0.3F;
            this.mane.xRot = Mth.sin(age * 0.3F) * 0.05F;
        }
    }

    // --- Ashen Knight ------------------------------------------------------------------------------------------

    public static class AshenKnightModel extends EntityModel<KnightState> {
        private final ModelPart head;
        private final ModelPart body;
        private final ModelPart rightArm;
        private final ModelPart leftArm;
        private final ModelPart rightLeg;
        private final ModelPart leftLeg;

        public AshenKnightModel(ModelPart root) {
            super(root);
            this.head = root.getChild("head");
            this.body = root.getChild("body");
            this.rightArm = root.getChild("right_arm");
            this.leftArm = root.getChild("left_arm");
            this.rightLeg = root.getChild("right_leg");
            this.leftLeg = root.getChild("left_leg");
        }

        @Override
        public void setupAnim(KnightState state) {
            super.setupAnim(state);
            float pos = state.walkAnimationPos;
            float speed = state.walkAnimationSpeed;
            this.head.yRot = state.yRot * DEG;
            this.head.xRot = state.xRot * DEG;
            this.rightLeg.xRot = Mth.cos(pos * 0.6662F) * 1.2F * speed;
            this.leftLeg.xRot = Mth.cos(pos * 0.6662F + Mth.PI) * 1.2F * speed;
            this.rightArm.xRot = Mth.cos(pos * 0.6662F + Mth.PI) * 0.6F * speed - 0.3F;
            this.leftArm.xRot = Mth.cos(pos * 0.6662F) * 0.4F * speed - 0.2F;
            if (state.guarding) {
                this.leftArm.xRot = -0.85F;
                this.leftArm.yRot = 0.45F;
            }
            if (state.cleaveTicks > 0.0F) {
                float t = state.cleaveTicks;
                if (t < AshenKnightEntity.CLEAVE_WINDUP) {
                    float raise = ease(t / (AshenKnightEntity.CLEAVE_WINDUP - 2.0F));
                    this.rightArm.xRot = -2.9F * raise;
                    this.rightArm.yRot = 0.5F * raise;
                } else {
                    float swing = ease((t - AshenKnightEntity.CLEAVE_WINDUP) / 4.0F);
                    this.rightArm.xRot = -2.9F + 3.4F * swing;
                    this.rightArm.yRot = 0.5F - 1.4F * swing;
                    this.body.yRot = -0.4F * swing;
                }
            } else if (state.attackTime > 0.0F) {
                float swing = Mth.sin(state.attackTime * Mth.PI);
                this.rightArm.xRot = -1.8F + swing * 1.6F;
            }
        }
    }

    // --- Solar Phoenix -----------------------------------------------------------------------------------------

    public static class SolarPhoenixModel extends EntityModel<PhoenixState> {
        private final ModelPart body;
        private final ModelPart neck;
        private final ModelPart head;
        private final ModelPart rightWing;
        private final ModelPart rightTip;
        private final ModelPart leftWing;
        private final ModelPart leftTip;
        private final ModelPart tail;

        public SolarPhoenixModel(ModelPart root) {
            super(root);
            this.body = root.getChild("body");
            this.neck = this.body.getChild("neck");
            this.head = this.neck.getChild("head");
            this.rightWing = this.body.getChild("right_wing");
            this.rightTip = this.rightWing.getChild("right_wing_tip");
            this.leftWing = this.body.getChild("left_wing");
            this.leftTip = this.leftWing.getChild("left_wing_tip");
            this.tail = this.body.getChild("tail");
        }

        @Override
        public void setupAnim(PhoenixState state) {
            super.setupAnim(state);
            float age = state.ageInTicks;
            float rate = state.ridden ? 0.45F : 0.3F;
            float t = age * rate;
            float amp = 0.75F;
            this.rightWing.zRot = Mth.sin(t) * amp;
            this.rightTip.zRot = Mth.sin(t - 0.8F) * amp * 0.7F;
            this.leftWing.zRot = -Mth.sin(t) * amp;
            this.leftTip.zRot = -Mth.sin(t - 0.8F) * amp * 0.7F;
            this.body.y += Mth.cos(t) * 1.2F;
            this.body.xRot = state.xRot * DEG * 0.5F;
            this.neck.xRot = -0.6F + Mth.sin(age * 0.1F) * 0.05F;
            this.head.xRot = 0.6F;
            this.head.yRot = state.yRot * DEG * 0.5F;
            this.tail.xRot = 0.25F + Mth.sin(t + 1.0F) * 0.12F;
            this.tail.yRot = Mth.sin(age * 0.06F) * 0.15F;
        }
    }

    // --- Sun Warden --------------------------------------------------------------------------------------------

    public static class SunWardenModel extends EntityModel<WardenState> {
        private final ModelPart waist;
        private final ModelPart torso;
        private final ModelPart head;
        private final ModelPart halo;
        private final ModelPart rightArm;
        private final ModelPart leftArm;
        private final ModelPart rightLeg;
        private final ModelPart leftLeg;
        private final ModelPart sword;

        public SunWardenModel(ModelPart root) {
            super(root);
            this.waist = root.getChild("waist");
            this.torso = this.waist.getChild("torso");
            this.head = this.torso.getChild("head");
            this.halo = this.torso.getChild("halo");
            this.rightArm = root.getChild("right_arm");
            this.leftArm = root.getChild("left_arm");
            this.rightLeg = root.getChild("right_leg");
            this.leftLeg = root.getChild("left_leg");
            this.sword = ModLayers.path(this.rightArm, "right_gauntlet/sword");
        }

        private void arms(float rx, float lx, float rz, float lz) {
            this.rightArm.xRot = rx;
            this.leftArm.xRot = lx;
            this.rightArm.zRot = rz;
            this.leftArm.zRot = lz;
        }

        private void lower(float amount) {
            this.waist.y += amount;
            this.rightArm.y += amount;
            this.leftArm.y += amount;
        }

        @Override
        public void setupAnim(WardenState state) {
            super.setupAnim(state);
            float pos = state.walkAnimationPos;
            float speed = Math.min(1.0F, state.walkAnimationSpeed);
            float age = state.ageInTicks;
            this.head.yRot = state.yRot * DEG * 0.8F;
            this.head.xRot = state.xRot * DEG * 0.6F;
            this.halo.zRot = age * (state.phase == SunWardenEntity.PHASE_SUPERNOVA ? 0.12F : 0.025F);
            float pulse = 1.0F + Mth.sin(age * 0.15F) * 0.04F;
            this.halo.xScale = pulse;
            this.halo.yScale = pulse;
            this.rightLeg.xRot = Mth.cos(pos * 0.5F) * 0.7F * speed;
            this.leftLeg.xRot = Mth.cos(pos * 0.5F + Mth.PI) * 0.7F * speed;
            this.arms(Mth.cos(pos * 0.5F + Mth.PI) * 0.4F * speed - 0.15F, Mth.cos(pos * 0.5F) * 0.4F * speed, 0.08F, -0.08F);
            this.torso.zRot = Mth.cos(pos * 0.5F) * 0.04F * speed;
            this.waist.y += Math.abs(Mth.sin(pos * 0.5F)) * -1.2F * speed;

            float t = state.attackTicks;
            switch (state.attack) {
                case SunWardenEntity.ATTACK_SUNFALL -> {
                    float up = ease(t / 14.0F);
                    this.arms(-2.9F * up, -0.4F * up, 0.1F, -0.5F * up);
                    this.head.xRot -= 0.5F * up;
                }
                case SunWardenEntity.ATTACK_BEAM -> {
                    float c = ease(t / 20.0F);
                    this.arms(-0.6F * c, -0.6F * c, 0.8F * c, -0.8F * c);
                    this.torso.xRot = -0.18F * c;
                }
                case SunWardenEntity.ATTACK_PILLARS -> {
                    float phase = (t % 20.0F) / 20.0F;
                    float raise = phase < 0.5F ? ease(phase * 2.0F) : 1.0F - ease((phase - 0.5F) * 4.0F);
                    this.arms(-2.4F * raise, -2.4F * raise, 0.0F, 0.0F);
                    this.torso.xRot = 0.25F * (1.0F - raise);
                }
                case SunWardenEntity.ATTACK_SLAM -> {
                    if (t < 8) {
                        float crouch = ease(t / 8.0F);
                        this.lower(3.0F * crouch);
                        this.arms(-0.8F * crouch, -0.8F * crouch, 0.0F, 0.0F);
                    } else if (t < 60) {
                        this.arms(-3.0F, -3.0F, 0.2F, -0.2F);
                    } else {
                        float s = ease((t - 60.0F) / 5.0F);
                        this.arms(-3.0F + 2.2F * s, -3.0F + 2.2F * s, 0.0F, 0.0F);
                        this.lower(3.0F * (1.0F - s));
                        this.torso.xRot = 0.35F * (1.0F - s);
                    }
                }
                case SunWardenEntity.ATTACK_SWEEP -> {
                    if (t < SunWardenEntity.SWEEP_HIT) {
                        float wind = ease(t / (SunWardenEntity.SWEEP_HIT - 2.0F));
                        this.rightArm.xRot = -1.6F * wind;
                        this.rightArm.yRot = 1.1F * wind;
                        this.torso.yRot = 0.4F * wind;
                    } else {
                        float s = ease((t - SunWardenEntity.SWEEP_HIT) / 4.0F);
                        this.rightArm.xRot = -1.6F;
                        this.rightArm.yRot = 1.1F - 2.4F * s;
                        this.torso.yRot = 0.4F - 0.9F * s;
                    }
                }
                case SunWardenEntity.ATTACK_SUMMON -> {
                    float up = ease(t / 15.0F);
                    this.arms(-2.0F * up, -2.0F * up, 0.9F * up, -0.9F * up);
                    this.head.xRot -= 0.4F * up;
                }
                case SunWardenEntity.ATTACK_CORONA -> {
                    if (t < 25) {
                        float c = ease(t / 20.0F);
                        this.arms(-1.4F * c, -1.4F * c, -0.6F * c, 0.6F * c);
                    } else {
                        float s = ease((t - 25.0F) / 4.0F);
                        this.arms(-1.4F, -1.4F, -0.6F + 1.8F * s, 0.6F - 1.8F * s);
                    }
                }
                default -> {
                }
            }
            if (state.phase == SunWardenEntity.PHASE_SUPERNOVA || state.phase == SunWardenEntity.PHASE_STUNNED) {
                // Kneels with the blade planted.
                this.lower(6.0F);
                this.rightLeg.xRot = -1.5F;
                this.rightLeg.z -= 3.0F;
                this.leftLeg.xRot = 0.0F;
                this.leftLeg.y += 2.0F;
                this.arms(-0.9F, -0.4F, 0.0F, 0.0F);
                this.sword.xRot = -0.2F;
                this.torso.xRot = state.phase == SunWardenEntity.PHASE_STUNNED ? 0.45F : 0.1F;
                this.head.xRot = state.phase == SunWardenEntity.PHASE_STUNNED ? 0.5F : -0.3F;
            }
            if (state.phase == SunWardenEntity.PHASE_RISING) {
                float reach = 1.0F - ease(state.rise / (float) SunWardenEntity.RISE_TICKS);
                this.arms(-2.8F + 1.0F * reach, -2.8F + 1.0F * reach, 0.3F, -0.3F);
                this.head.xRot = -0.4F;
            }
            if (state.dying) {
                this.lower(6.0F);
                this.rightLeg.xRot = -1.5F;
                this.rightLeg.z -= 3.0F;
                this.leftLeg.y += 2.0F;
                this.arms(-0.3F, -0.3F, 0.5F, -0.5F);
                this.head.xRot = -0.8F + Mth.sin(age * 2.0F) * 0.05F;
                this.torso.xRot = -0.3F;
            }
        }
    }

    // --- Solar Pylon -------------------------------------------------------------------------------------------

    public static class SolarPylonModel extends Model<PylonState> {
        private final ModelPart top;

        public SolarPylonModel(ModelPart root) {
            super(root, RenderTypes::entityCutout);
            this.top = root.getChild("top");
        }

        @Override
        public void setupAnim(PylonState state) {
            super.setupAnim(state);
            float age = state.ageInTicks;
            this.top.yRot = age * 0.08F;
            this.top.y += Mth.sin(age * 0.12F) * 1.2F;
        }
    }
}
