package com.starforged.tempest;

import com.starforged.Starforged;
import net.minecraft.sounds.SoundEvent;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

/** Every sound of the Tempestforged expansion (files generated by tools/gen_tempest_sounds.py). */
public final class TempestSounds {
    public static final DeferredRegister<SoundEvent> SOUNDS = DeferredRegister.create(ForgeRegistries.SOUND_EVENTS, Starforged.MODID);

    // World
    public static final RegistryObject<SoundEvent> GATEWAY_FORM = register("item.skybreaker_core.forge");
    public static final RegistryObject<SoundEvent> GATEWAY_TRAVEL = register("block.stormgate.travel");
    public static final RegistryObject<SoundEvent> STORM_WIND = register("ambient.stormreach.wind");
    public static final RegistryObject<SoundEvent> GUST = register("ambient.stormreach.gust");
    public static final RegistryObject<SoundEvent> SUPERCELL = register("event.supercell");
    public static final RegistryObject<SoundEvent> CHARGE = register("item.aetherium.charge");
    public static final RegistryObject<SoundEvent> WIND_VENT = register("block.wind_vent.blow");
    public static final RegistryObject<SoundEvent> SHOCK_PLATE = register("block.shock_plate.zap");
    public static final RegistryObject<SoundEvent> CHIME = register("block.wind_chime.chime");
    public static final RegistryObject<SoundEvent> CONDUCTOR_TURN = register("block.rotating_conductor.turn");
    public static final RegistryObject<SoundEvent> NETWORK_PULSE = register("block.storm_network.pulse");
    public static final RegistryObject<SoundEvent> CORE_ONLINE = register("block.citadel_core.online");
    public static final RegistryObject<SoundEvent> OVERLOAD = register("block.overload_relay.overload");
    public static final RegistryObject<SoundEvent> SEAL_OPEN = register("block.tempest_seal.open");
    public static final RegistryObject<SoundEvent> ALTAR_ACTIVATE = register("block.tempest_altar.activate");

    // Items
    public static final RegistryObject<SoundEvent> DASH = register("item.stormstep.dash");
    public static final RegistryObject<SoundEvent> HALBERD_LAUNCH = register("item.skybreaker_halberd.launch");
    public static final RegistryObject<SoundEvent> HALBERD_SLAM = register("item.skybreaker_halberd.slam");
    public static final RegistryObject<SoundEvent> JAVELIN_THROW = register("item.tempest_javelin.throw");
    public static final RegistryObject<SoundEvent> JAVELIN_RECALL = register("item.tempest_javelin.recall");
    public static final RegistryObject<SoundEvent> BLADES_CYCLONE = register("item.gale_blades.cyclone");
    public static final RegistryObject<SoundEvent> HOOK_FIRE = register("item.stormhook.fire");
    public static final RegistryObject<SoundEvent> LIVE_WIRE = register("item.stormhook.live_wire");
    public static final RegistryObject<SoundEvent> CANNON_CHARGE = register("item.arc_cannon.charge");
    public static final RegistryObject<SoundEvent> CANNON_FIRE = register("item.arc_cannon.fire");
    public static final RegistryObject<SoundEvent> JUDGEMENT = register("item.skycleaver.judgement");

    // Creatures
    public static final RegistryObject<SoundEvent> WISP_AMBIENT = register("entity.static_wisp.ambient");
    public static final RegistryObject<SoundEvent> WISP_ARC = register("entity.static_wisp.arc");
    public static final RegistryObject<SoundEvent> WISP_DEATH = register("entity.static_wisp.death");
    public static final RegistryObject<SoundEvent> SHARDWING_AMBIENT = register("entity.shardwing.ambient");
    public static final RegistryObject<SoundEvent> SHARDWING_DIVE = register("entity.shardwing.dive");
    public static final RegistryObject<SoundEvent> SHARDWING_DEATH = register("entity.shardwing.death");
    public static final RegistryObject<SoundEvent> STORMBOUND_AMBIENT = register("entity.stormbound.ambient");
    public static final RegistryObject<SoundEvent> STORMBOUND_STEP = register("entity.stormbound.thunderstep");
    public static final RegistryObject<SoundEvent> STORMBOUND_DEATH = register("entity.stormbound.death");
    public static final RegistryObject<SoundEvent> THUNDERJAW_AMBIENT = register("entity.thunderjaw.ambient");
    public static final RegistryObject<SoundEvent> THUNDERJAW_STAMP = register("entity.thunderjaw.stamp");
    public static final RegistryObject<SoundEvent> THUNDERJAW_DEATH = register("entity.thunderjaw.death");
    public static final RegistryObject<SoundEvent> SPRITE_AMBIENT = register("entity.zephyr_sprite.ambient");
    public static final RegistryObject<SoundEvent> SPRITE_GUARD = register("entity.zephyr_sprite.windguard");
    public static final RegistryObject<SoundEvent> ROC_AMBIENT = register("entity.storm_roc.ambient");
    public static final RegistryObject<SoundEvent> ROC_SCREECH = register("entity.storm_roc.screech");
    public static final RegistryObject<SoundEvent> ALPHA_ROAR = register("entity.thunderjaw_alpha.roar");

    // Boss
    public static final RegistryObject<SoundEvent> VEYR_ROAR = register("entity.veyr.roar");
    public static final RegistryObject<SoundEvent> VEYR_HURT = register("entity.veyr.hurt");
    public static final RegistryObject<SoundEvent> VEYR_DEATH = register("entity.veyr.death");
    public static final RegistryObject<SoundEvent> VEYR_THUNDERSTEP = register("entity.veyr.thunderstep");
    public static final RegistryObject<SoundEvent> VEYR_TORNADO = register("entity.veyr.tornado");
    public static final RegistryObject<SoundEvent> VEYR_SHATTER = register("entity.veyr.shatter");
    public static final RegistryObject<SoundEvent> VEYR_LAST_THUNDER = register("entity.veyr.last_thunder");
    public static final RegistryObject<SoundEvent> CONDUCTOR_REDIRECT = register("entity.storm_conductor.redirect");

    private static RegistryObject<SoundEvent> register(String name) {
        return SOUNDS.register(name, () -> SoundEvent.createVariableRangeEvent(Starforged.id(name)));
    }

    private TempestSounds() {
    }
}
