package com.starforged.moon;

import com.starforged.Starforged;
import net.minecraft.sounds.SoundEvent;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

/** Every sound of the Moonforged expansion (files generated by tools/gen_moon_sounds.py). */
public final class MoonSounds {
    public static final DeferredRegister<SoundEvent> SOUNDS = DeferredRegister.create(ForgeRegistries.SOUND_EVENTS, Starforged.MODID);

    // World
    public static final RegistryObject<SoundEvent> GATEWAY_FORM = register("item.lunar_key.forge");
    public static final RegistryObject<SoundEvent> GATEWAY_TRAVEL = register("block.lunar_gateway.travel");
    public static final RegistryObject<SoundEvent> TIDE_HIGH = register("event.tide.high");
    public static final RegistryObject<SoundEvent> TIDE_LOW = register("event.tide.low");
    public static final RegistryObject<SoundEvent> CLAM_OPEN = register("block.tidal_clam.open");
    public static final RegistryObject<SoundEvent> GRAVITY_PLATE = register("block.gravity_plate.launch");
    public static final RegistryObject<SoundEvent> RING_TURN = register("block.orrery_ring.turn");
    public static final RegistryObject<SoundEvent> ORRERY_ALIGN = register("block.orrery.align");
    public static final RegistryObject<SoundEvent> ORRERY_FAIL = register("block.orrery.misalign");
    public static final RegistryObject<SoundEvent> MOON_SEAL_OPEN = register("block.moon_seal.open");
    public static final RegistryObject<SoundEvent> MOON_ALTAR_ACTIVATE = register("block.moon_altar.activate");

    // Items
    public static final RegistryObject<SoundEvent> GLAIVE_THROW = register("item.crescent_glaive.throw");
    public static final RegistryObject<SoundEvent> STAFF_FIRE = register("item.orrery_staff.fire");
    public static final RegistryObject<SoundEvent> STAFF_MOONFALL = register("item.orrery_staff.moonfall");
    public static final RegistryObject<SoundEvent> DAGGER_PHASE = register("item.phase_daggers.dash");
    public static final RegistryObject<SoundEvent> DAGGER_DETONATE = register("item.phase_daggers.detonate");
    public static final RegistryObject<SoundEvent> BOLT_RICOCHET = register("item.moonshot_crossbow.ricochet");
    public static final RegistryObject<SoundEvent> BELL_RING = register("item.stasis_bell.ring");
    public static final RegistryObject<SoundEvent> HOOK_FIRE = register("item.tether_hook.fire");
    public static final RegistryObject<SoundEvent> TIDE_WAVE = register("item.tidecaller_glaive.wave");
    public static final RegistryObject<SoundEvent> WARD_BREAK = register("item.lunar_ward.break");

    // Creatures
    public static final RegistryObject<SoundEvent> SKIMMER_AMBIENT = register("entity.regolith_skimmer.ambient");
    public static final RegistryObject<SoundEvent> SKIMMER_ERUPT = register("entity.regolith_skimmer.erupt");
    public static final RegistryObject<SoundEvent> SKIMMER_DEATH = register("entity.regolith_skimmer.death");
    public static final RegistryObject<SoundEvent> MOTH_AMBIENT = register("entity.lunar_moth.ambient");
    public static final RegistryObject<SoundEvent> MOTH_EAT = register("entity.lunar_moth.eat");
    public static final RegistryObject<SoundEvent> MOTH_DEATH = register("entity.lunar_moth.death");
    public static final RegistryObject<SoundEvent> SENTINEL_AMBIENT = register("entity.selenite_sentinel.ambient");
    public static final RegistryObject<SoundEvent> SENTINEL_REFLECT = register("entity.selenite_sentinel.reflect");
    public static final RegistryObject<SoundEvent> SENTINEL_DEATH = register("entity.selenite_sentinel.death");
    public static final RegistryObject<SoundEvent> LURKER_AMBIENT = register("entity.umbral_lurker.ambient");
    public static final RegistryObject<SoundEvent> LURKER_LUNGE = register("entity.umbral_lurker.lunge");
    public static final RegistryObject<SoundEvent> LURKER_DEATH = register("entity.umbral_lurker.death");
    public static final RegistryObject<SoundEvent> MOONKIT_AMBIENT = register("entity.moonkit.ambient");
    public static final RegistryObject<SoundEvent> MOONKIT_SNIFF = register("entity.moonkit.sniff");
    public static final RegistryObject<SoundEvent> LEAPER_AMBIENT = register("entity.moonleaper.ambient");
    public static final RegistryObject<SoundEvent> LEAPER_LEAP = register("entity.moonleaper.leap");

    // Boss
    public static final RegistryObject<SoundEvent> MATRIARCH_ROAR = register("entity.pale_matriarch.roar");
    public static final RegistryObject<SoundEvent> MATRIARCH_HURT = register("entity.pale_matriarch.hurt");
    public static final RegistryObject<SoundEvent> MATRIARCH_DEATH = register("entity.pale_matriarch.death");
    public static final RegistryObject<SoundEvent> MATRIARCH_WAVE = register("entity.pale_matriarch.wave");
    public static final RegistryObject<SoundEvent> MATRIARCH_LANCE = register("entity.pale_matriarch.lance");
    public static final RegistryObject<SoundEvent> MATRIARCH_TELEPORT = register("entity.pale_matriarch.teleport");
    public static final RegistryObject<SoundEvent> MATRIARCH_INVERSION = register("entity.pale_matriarch.inversion");
    public static final RegistryObject<SoundEvent> MATRIARCH_MOONFALL = register("entity.pale_matriarch.moonfall");
    public static final RegistryObject<SoundEvent> ANCHOR_SHATTER = register("entity.lunar_anchor.shatter");

    private static RegistryObject<SoundEvent> register(String name) {
        return SOUNDS.register(name, () -> SoundEvent.createVariableRangeEvent(Starforged.id(name)));
    }

    private MoonSounds() {
    }
}
