#version 330 compatibility
// Generated by tools/shader/build_shader.py - edit program/gbuffers_unlit.glsl instead.
#define VSH
#define DIM_END
#define PROGRAM_SKYTEXTURED
#include "/program/gbuffers_unlit.glsl"
