#version 330 compatibility
// Generated by tools/shader/build_shader.py - edit program/gbuffers_water.glsl instead.
#define FSH
#define DIM_END
#define PROGRAM_HAND_WATER
#include "/program/gbuffers_water.glsl"
