#version 330 compatibility
// Generated by tools/shader/build_shader.py - edit program/gbuffers_lit.glsl instead.
#define FSH
#define DIM_END
#define PROGRAM_HAND
#include "/program/gbuffers_lit.glsl"
