#version 330 compatibility
// Generated by tools/shader/build_shader.py - edit program/gbuffers_lit.glsl instead.
#define VSH
#define DIM_END
#define PROGRAM_TERRAIN
#include "/program/gbuffers_lit.glsl"
