#!/usr/bin/env python3
"""Build Emberveil Shaders.

1. Generate per-program wrapper files for the Overworld (root), Nether (world-1) and End (world1).
2. Generate block/item/entity .properties material maps.
3. Static check: expand #includes like Iris does, prepend Iris' standard macros, and compile every
   program stage for every profile with glslangValidator (catches syntax/type errors only; it is not
   a substitute for running the pack in Iris).
4. Package dist/Emberveil-Shaders-<version>.zip (shaders/ at the zip root, plus LICENSE/README).
"""
import itertools, os, pathlib, re, shutil, subprocess, sys, zipfile

VERSION = "1.0.0"
ROOT = pathlib.Path(__file__).resolve().parents[2]
PACK = ROOT / "shader/Emberveil-Shaders"
SH = PACK / "shaders"

# program name -> (shared source, defines)
PROGRAMS = {
    "gbuffers_basic": ("gbuffers_unlit", ["PROGRAM_BASIC"]),
    "gbuffers_textured": ("gbuffers_unlit", []),
    "gbuffers_textured_lit": ("gbuffers_lit", ["PROGRAM_PARTICLES"]),
    "gbuffers_skybasic": ("gbuffers_sky", []),
    "gbuffers_skytextured": ("gbuffers_unlit", ["PROGRAM_SKYTEXTURED"]),
    "gbuffers_clouds": ("gbuffers_unlit", ["PROGRAM_CLOUDS"]),
    "gbuffers_terrain": ("gbuffers_lit", ["PROGRAM_TERRAIN"]),
    "gbuffers_damagedblock": ("gbuffers_lit", ["PROGRAM_DAMAGED"]),
    "gbuffers_block": ("gbuffers_lit", ["PROGRAM_BLOCK"]),
    "gbuffers_beaconbeam": ("gbuffers_unlit", ["PROGRAM_BEACON"]),
    "gbuffers_entities": ("gbuffers_lit", ["PROGRAM_ENTITIES"]),
    "gbuffers_armor_glint": ("gbuffers_unlit", ["PROGRAM_GLINT"]),
    "gbuffers_spidereyes": ("gbuffers_unlit", ["PROGRAM_EYES"]),
    "gbuffers_hand": ("gbuffers_lit", ["PROGRAM_HAND"]),
    "gbuffers_weather": ("gbuffers_unlit", ["PROGRAM_WEATHER"]),
    "gbuffers_water": ("gbuffers_water", []),
    "gbuffers_hand_water": ("gbuffers_water", ["PROGRAM_HAND_WATER"]),
    "shadow": ("shadow", []),
    "composite": ("composite", []),
    "composite1": ("bloom", ["BLOOM_PREFILTER"]),
    "composite2": ("bloom", ["BLOOM_GATHER"]),
    "final": ("final", []),
}
DIMENSIONS = {"": [], "world-1": ["DIM_NETHER"], "world1": ["DIM_END"]}
NO_SHADOW_DIMS = {"world-1", "world1"}   # no sun in the Nether/End: skip the shadow pass entirely

def gen_wrappers():
    for dim, ddefs in DIMENSIONS.items():
        d = SH / dim if dim else SH
        d.mkdir(parents=True, exist_ok=True)
        for f in d.glob("*.vsh"): f.unlink()
        for f in d.glob("*.fsh"): f.unlink()
        for prog, (src, defs) in PROGRAMS.items():
            if prog == "shadow" and dim in NO_SHADOW_DIMS:
                continue
            for stage, sdef in (("vsh", "VSH"), ("fsh", "FSH")):
                lines = ["#version 330 compatibility", f"// Generated by tools/shader/build_shader.py - edit program/{src}.glsl instead."]
                lines += [f"#define {x}" for x in [sdef] + ddefs + defs]
                lines.append(f'#include "/program/{src}.glsl"')
                (d / f"{prog}.{stage}").write_text("\n".join(lines) + "\n")

CANDLES = ["candle"] + [f"{c}_candle" for c in "white orange magenta light_blue yellow lime pink gray light_gray cyan purple blue brown green red black".split()]
BLOCKS = {
    10001: "minecraft:water minecraft:bubble_column",
    10002: " ".join([
        "minecraft:short_grass minecraft:fern minecraft:dead_bush minecraft:sweet_berry_bush",
        "minecraft:wheat minecraft:carrots minecraft:potatoes minecraft:beetroots minecraft:torchflower_crop",
        "minecraft:tall_grass:half=lower minecraft:large_fern:half=lower minecraft:sunflower:half=lower",
        "minecraft:lilac:half=lower minecraft:rose_bush:half=lower minecraft:peony:half=lower minecraft:pitcher_plant:half=lower",
        "%minecraft:small_flowers %minecraft:saplings %minecraft:crops"]),
    10003: "%minecraft:leaves minecraft:azalea minecraft:flowering_azalea",
    10004: "minecraft:vine minecraft:weeping_vines minecraft:weeping_vines_plant minecraft:twisting_vines minecraft:twisting_vines_plant "
           "minecraft:cave_vines:berries=false minecraft:cave_vines_plant:berries=false minecraft:hanging_roots",
    10005: "minecraft:tall_grass:half=upper minecraft:large_fern:half=upper minecraft:sunflower:half=upper minecraft:lilac:half=upper "
           "minecraft:rose_bush:half=upper minecraft:peony:half=upper minecraft:pitcher_plant:half=upper",
    10006: "minecraft:seagrass minecraft:tall_seagrass minecraft:kelp minecraft:kelp_plant",
    10010: "minecraft:torch minecraft:wall_torch minecraft:soul_torch minecraft:soul_wall_torch minecraft:lantern minecraft:soul_lantern "
           "minecraft:redstone_torch:lit=true minecraft:redstone_wall_torch:lit=true minecraft:end_rod minecraft:campfire:lit=true "
           "minecraft:soul_campfire:lit=true minecraft:magma_block " + " ".join(f"minecraft:{c}:lit=true" for c in CANDLES),
    10011: "minecraft:lava",
    10012: "minecraft:glowstone minecraft:sea_lantern minecraft:shroomlight minecraft:ochre_froglight minecraft:verdant_froglight "
           "minecraft:pearlescent_froglight minecraft:redstone_lamp:lit=true minecraft:jack_o_lantern minecraft:beacon",
    10013: "minecraft:fire minecraft:soul_fire",
    10014: "minecraft:crying_obsidian minecraft:glow_lichen minecraft:sea_pickle minecraft:amethyst_cluster minecraft:large_amethyst_bud "
           "minecraft:sculk_catalyst minecraft:sculk_sensor minecraft:calibrated_sculk_sensor minecraft:respawn_anchor "
           "minecraft:cave_vines:berries=true minecraft:cave_vines_plant:berries=true minecraft:redstone_ore:lit=true "
           "minecraft:deepslate_redstone_ore:lit=true",
    10040: "minecraft:end_portal minecraft:end_gateway",
    10041: "minecraft:nether_portal",
}
ITEMS = {
    10010: "minecraft:torch minecraft:soul_torch minecraft:lantern minecraft:soul_lantern minecraft:redstone_torch minecraft:end_rod "
           "minecraft:campfire minecraft:soul_campfire minecraft:magma_block minecraft:lava_bucket",
    10012: "minecraft:glowstone minecraft:sea_lantern minecraft:shroomlight minecraft:ochre_froglight minecraft:verdant_froglight "
           "minecraft:pearlescent_froglight minecraft:jack_o_lantern minecraft:beacon",
    10014: "minecraft:glow_berries minecraft:glow_ink_sac minecraft:blaze_rod minecraft:blaze_powder minecraft:nether_star",
}
ENTITIES = {
    20001: "minecraft:blaze minecraft:magma_cube minecraft:glow_squid minecraft:allay minecraft:experience_orb",
}
EXTRA_ENTITIES_FILE = ROOT / "tools/shader/emissive_entities.txt"   # modded ids, verified against the registry dump
EXTRA_BLOCKS_FILE = ROOT / "tools/shader/emissive_blocks.txt"

def write_props(path, prefix, table, header):
    out = [f"# {header}", "# Generated by tools/shader/build_shader.py", ""]
    for k in sorted(table):
        out.append(f"{prefix}.{k}={table[k]}")
    path.write_text("\n".join(out) + "\n")

def gen_properties():
    blocks = dict(BLOCKS)
    ents = dict(ENTITIES)
    if EXTRA_ENTITIES_FILE.exists():
        extra = " ".join(l.split("#")[0].strip() for l in EXTRA_ENTITIES_FILE.read_text().splitlines() if l.split("#")[0].strip())
        if extra: ents[20001] += " " + extra
    if EXTRA_BLOCKS_FILE.exists():
        for l in EXTRA_BLOCKS_FILE.read_text().splitlines():
            l = l.split("#")[0].strip()
            if l:
                bid, names = l.split("=", 1)
                blocks[int(bid)] = (blocks.get(int(bid), "") + " " + names.strip()).strip()
    write_props(SH / "block.properties", "block", blocks, "Emberveil Shaders material ids (see lib/common.glsl)")
    write_props(SH / "item.properties", "item", ITEMS, "Held/dropped item ids for glowing items")
    write_props(SH / "entity.properties", "entity", ents, "Entities with glowing parts")

def expand(path, seen=None, depth=0):
    """Resolve #include "/..." like Iris (absolute from shaders/), keeping line structure simple."""
    text = path.read_text()
    out = []
    for line in text.splitlines():
        m = re.match(r'\s*#include\s+"(/[^"]+)"', line)
        if m:
            out.append(expand(SH / m.group(1).lstrip("/"), seen, depth + 1))
        else:
            out.append(line)
    return "\n".join(out)

IRIS_MACROS = """#define MC_VERSION 12101
#define MC_GL_VERSION 450
#define MC_GLSL_VERSION 450
#define MC_RENDER_STAGE_NONE 0
#define MC_RENDER_STAGE_SKY 1
#define MC_RENDER_STAGE_SUNSET 2
#define MC_RENDER_STAGE_CUSTOM_SKY 3
#define MC_RENDER_STAGE_SUN 4
#define MC_RENDER_STAGE_MOON 5
#define MC_RENDER_STAGE_STARS 6
#define MC_RENDER_STAGE_VOID 7
#define MC_RENDER_STAGE_OUTLINE 15
"""

def static_check():
    glslang = shutil.which("glslangValidator")
    if not glslang:
        print("static check skipped: glslangValidator not installed"); return True
    # option sets = the three profiles
    props = (SH / "shaders.properties").read_text()
    profiles = dict(re.findall(r"^profile\.(\w+)=(.*)$", props, re.M))
    ok = True
    tmp = ROOT / ".cache/shadercheck"; tmp.mkdir(parents=True, exist_ok=True)
    for pname, pdef in profiles.items():
        defs = []
        for tok in pdef.split():
            if tok.startswith("!"): defs.append(("UNDEF", tok[1:]))
            elif "=" in tok:
                k, v = tok.split("=", 1)
                defs.append(("SET", k, v))
            else: defs.append(("DEF", tok))
        for dim in DIMENSIONS:
            d = SH / dim if dim else SH
            for f in sorted(list(d.glob("*.vsh")) + list(d.glob("*.fsh"))):
                src = expand(f)
                lines = src.splitlines()
                assert lines[0].startswith("#version")
                body = "\n".join(lines[1:])
                # Apply profile values the way Iris rewrites option #defines / consts.
                for dd in defs:
                    if dd[0] == "DEF":
                        body = re.sub(rf"^//\s*#define {dd[1]}\b", f"#define {dd[1]}", body, flags=re.M)
                    elif dd[0] == "UNDEF":
                        body = re.sub(rf"^#define {dd[1]}\b(?!\s+\S)", f"//#define {dd[1]}", body, flags=re.M)
                    else:
                        body = re.sub(rf"^(#define {dd[1]}\s+)\S+", rf"\g<1>{dd[2]}", body, flags=re.M)
                        body = re.sub(rf"^(const\s+\w+\s+{dd[1]}\s*=\s*)[^;]+", rf"\g<1>{dd[2]}", body, flags=re.M)
                full = "#version 450 compatibility\n" + IRIS_MACROS + body
                stage = "vert" if f.suffix == ".vsh" else "frag"
                out = tmp / f"{pname}_{dim or 'root'}_{f.stem}.{stage}"
                out.write_text(full)
                r = subprocess.run([glslang, "-S", stage, str(out)], capture_output=True, text=True)
                if r.returncode != 0:
                    ok = False
                    print(f"FAIL [{pname}] {dim or 'overworld'}/{f.name}\n" + "\n".join(l for l in r.stdout.splitlines() if "ERROR" in l)[:2000])
    print("static check:", "all programs compiled for all profiles" if ok else "ERRORS")
    return ok

def package():
    dist = ROOT / "dist"; dist.mkdir(exist_ok=True)
    zpath = dist / f"Emberveil-Shaders-{VERSION}.zip"
    if zpath.exists(): zpath.unlink()
    with zipfile.ZipFile(zpath, "w", zipfile.ZIP_DEFLATED) as z:
        for p in sorted(PACK.rglob("*")):
            if p.is_file():
                z.write(p, p.relative_to(PACK).as_posix())
    print("packaged", zpath, zpath.stat().st_size, "bytes")
    return zpath

if __name__ == "__main__":
    gen_wrappers()
    gen_properties()
    ok = static_check() if "--no-check" not in sys.argv else True
    if "--package" in sys.argv:
        package()
    sys.exit(0 if ok else 1)
