package com.starforged.tempest.client;

import com.starforged.client.model.ModLayers;
import com.starforged.client.render.StarforgedRenderStates.CreatureState;
import com.starforged.tempest.boss.VeyrEntity;
import com.starforged.tempest.client.TempestRenderStates.BeastState;
import com.starforged.tempest.client.TempestRenderStates.ComboState;
import com.starforged.tempest.client.TempestRenderStates.ConductorState;
import com.starforged.tempest.client.TempestRenderStates.DiveState;
import com.starforged.tempest.client.TempestRenderStates.RocState;
import com.starforged.tempest.client.TempestRenderStates.SpriteState;
import com.starforged.tempest.client.TempestRenderStates.VeyrState;
import com.starforged.tempest.entity.ThunderjawEntity;
import net.minecraft.client.model.EntityModel;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.util.Mth;

/** Animated models for the Tempestforged creatures (geometry in ModelGeometry, generated by tools/gen_models.py). */
public final class TempestModels {
    private static final float DEG = Mth.DEG_TO_RAD;

    private TempestModels() {
    }

    // --- Static Wisp -----------------------------------------------------------------------------------------------

    public static class StaticWispModel extends EntityModel<CreatureState> {
        private final ModelPart core;
        private final ModelPart orbit;

        public StaticWispModel(ModelPart root) {
            super(root);
            this.core = root.getChild("core");
            this.orbit = this.core.getChild("orbit");
        }

        @Override
        public void setupAnim(CreatureState state) {
            super.setupAnim(state);
            float age = state.ageInTicks;
            this.core.y += Mth.sin(age * 0.15F) * 1.5F;
            this.core.yRot = age * 0.05F;
            this.orbit.yRot = age * 0.3F;
            this.orbit.xRot = Mth.sin(age * 0.07F) * 0.4F;
        }
    }

    // --- Shardwing -------------------------------------------------------------------------------------------------

    public static class ShardwingModel extends EntityModel<DiveState> {
        private final ModelPart body;
        private final ModelPart head;
        private final ModelPart rightWing;
        private final ModelPart leftWing;
        private final ModelPart rightTip;
        private final ModelPart leftTip;
        private final ModelPart tail;

        public ShardwingModel(ModelPart root) {
            super(root);
            this.body = root.getChild("body");
            this.head = root.getChild("head");
            this.rightWing = root.getChild("right_wing");
            this.leftWing = root.getChild("left_wing");
            this.rightTip = this.rightWing.getChild("right_wing_tip");
            this.leftTip = this.leftWing.getChild("left_wing_tip");
            this.tail = this.body.getChild("tail");
        }

        @Override
        public void setupAnim(DiveState state) {
            super.setupAnim(state);
            float age = state.ageInTicks;
            if (state.diving) {
                // Wings swept back into a crystal arrowhead.
                this.rightWing.yRot = 1.0F;
                this.leftWing.yRot = -1.0F;
                this.rightWing.zRot = 0.2F;
                this.leftWing.zRot = -0.2F;
                this.body.xRot = 0.5F;
                this.head.xRot = 0.5F;
            } else {
                float flap = Mth.sin(age * 0.6F) * 0.7F;
                this.rightWing.zRot = flap;
                this.leftWing.zRot = -flap;
                this.rightTip.zRot = flap * 0.6F;
                this.leftTip.zRot = -flap * 0.6F;
                this.head.yRot = state.yRot * DEG;
            }
            this.tail.xRot = Mth.sin(age * 0.2F) * 0.15F;
        }
    }

    // --- Stormbound ------------------------------------------------------------------------------------------------

    public static class StormboundModel extends EntityModel<ComboState> {
        private final ModelPart head;
        private final ModelPart rightArm;
        private final ModelPart leftArm;
        private final ModelPart rightLeg;
        private final ModelPart leftLeg;
        private final ModelPart body;

        public StormboundModel(ModelPart root) {
            super(root);
            this.head = root.getChild("head");
            this.body = root.getChild("body");
            this.rightArm = root.getChild("right_arm");
            this.leftArm = root.getChild("left_arm");
            this.rightLeg = root.getChild("right_leg");
            this.leftLeg = root.getChild("left_leg");
        }

        @Override
        public void setupAnim(ComboState state) {
            super.setupAnim(state);
            float pos = state.walkAnimationPos;
            float speed = Math.min(1.0F, state.walkAnimationSpeed);
            this.head.yRot = state.yRot * DEG;
            this.head.xRot = state.xRot * DEG;
            this.rightLeg.xRot = Mth.cos(pos * 0.6F) * 0.9F * speed;
            this.leftLeg.xRot = -Mth.cos(pos * 0.6F) * 0.9F * speed;
            this.leftArm.xRot = Mth.cos(pos * 0.6F) * 0.6F * speed;
            this.rightArm.xRot = -0.3F;
            int combo = state.combo;
            if (combo > 0) {
                // Three thrusts and a sweep, matching the server's hits at 6 / 14 / 24.
                if (combo < 10) {
                    float t = Mth.clamp((combo - 2) / 4.0F, 0.0F, 1.0F);
                    this.rightArm.xRot = -0.3F - t * 1.0F;
                    this.body.yRot = -t * 0.3F;
                } else if (combo < 18) {
                    float t = Mth.clamp((combo - 10) / 4.0F, 0.0F, 1.0F);
                    this.rightArm.xRot = -1.3F + t * 0.4F;
                    this.rightArm.yRot = -t * 0.8F;
                    this.body.yRot = t * 0.4F;
                } else {
                    float t = Mth.clamp((combo - 18) / 6.0F, 0.0F, 1.0F);
                    this.rightArm.xRot = -2.6F + t * 2.0F;
                    this.leftArm.xRot = -1.0F;
                }
            } else if (state.attackTime > 0.0F) {
                this.rightArm.xRot = -0.3F - Mth.sin(state.attackTime * Mth.PI) * 1.4F;
            }
        }
    }

    // --- Thunderjaw (and the Alpha) --------------------------------------------------------------------------------

    public static class ThunderjawModel extends EntityModel<BeastState> {
        private final ModelPart head;
        private final ModelPart jaw;
        private final ModelPart body;
        private final ModelPart rightFront;
        private final ModelPart leftFront;
        private final ModelPart rightHind;
        private final ModelPart leftHind;
        private final ModelPart tail;

        public ThunderjawModel(ModelPart root) {
            super(root);
            this.head = root.getChild("head");
            this.jaw = this.head.getChild("jaw");
            this.body = root.getChild("body");
            this.rightFront = root.getChild("right_front_leg");
            this.leftFront = root.getChild("left_front_leg");
            this.rightHind = root.getChild("right_hind_leg");
            this.leftHind = root.getChild("left_hind_leg");
            this.tail = root.getChild("tail");
        }

        @Override
        public void setupAnim(BeastState state) {
            super.setupAnim(state);
            float pos = state.walkAnimationPos;
            float speed = Math.min(1.0F, state.walkAnimationSpeed);
            float gait = state.rushing ? 0.9F : 0.5F;
            this.rightFront.xRot = Mth.cos(pos * gait) * 0.7F * speed;
            this.leftHind.xRot = Mth.cos(pos * gait) * 0.7F * speed;
            this.leftFront.xRot = -Mth.cos(pos * gait) * 0.7F * speed;
            this.rightHind.xRot = -Mth.cos(pos * gait) * 0.7F * speed;
            this.head.yRot = state.yRot * DEG * 0.5F;
            this.head.xRot = state.rushing ? 0.45F : state.xRot * DEG * 0.5F;
            this.jaw.xRot = 0.05F + (state.charged ? Mth.sin(state.ageInTicks * 0.5F) * 0.08F + 0.1F : 0.0F);
            this.tail.yRot = Mth.sin(state.ageInTicks * 0.1F) * 0.2F;
            int stamp = state.stamp;
            if (stamp > 0) {
                // Rear up on the hind legs, then slam both forefeet down.
                float rise = stamp < ThunderjawEntity.STAMP_HIT ? stamp / (float) ThunderjawEntity.STAMP_HIT
                    : 1.0F - Math.min(1.0F, (stamp - ThunderjawEntity.STAMP_HIT) / 3.0F);
                this.body.xRot = -rise * 0.55F;
                this.head.xRot = -rise * 0.6F;
                this.head.y -= rise * 6.0F;
                this.head.z += rise * 3.0F;
                this.rightFront.xRot = -rise * 1.3F;
                this.leftFront.xRot = -rise * 1.3F;
                this.rightFront.y -= rise * 6.0F;
                this.leftFront.y -= rise * 6.0F;
                this.jaw.xRot = rise * 0.7F;
            }
        }
    }

    // --- Zephyr Sprite ---------------------------------------------------------------------------------------------

    public static class ZephyrSpriteModel extends EntityModel<SpriteState> {
        private final ModelPart body;
        private final ModelPart head;
        private final ModelPart swirl;
        private final ModelPart rightWing;
        private final ModelPart leftWing;

        public ZephyrSpriteModel(ModelPart root) {
            super(root);
            this.body = root.getChild("body");
            this.head = root.getChild("head");
            this.swirl = this.body.getChild("swirl");
            this.rightWing = root.getChild("right_wing");
            this.leftWing = root.getChild("left_wing");
        }

        @Override
        public void setupAnim(SpriteState state) {
            super.setupAnim(state);
            float age = state.ageInTicks;
            float bob = state.sitting ? 3.0F : Mth.sin(age * 0.2F) * 1.2F;
            this.body.y += bob;
            this.head.y += bob;
            this.rightWing.y += bob;
            this.leftWing.y += bob;
            float flap = state.sitting ? 0.2F : Mth.sin(age * 1.4F) * 0.6F;
            this.rightWing.yRot = -0.35F - flap;
            this.leftWing.yRot = 0.35F + flap;
            this.swirl.yRot = age * 0.6F;
            this.head.yRot = state.yRot * DEG;
            this.head.xRot = state.xRot * DEG;
        }
    }

    // --- Storm Roc -------------------------------------------------------------------------------------------------

    public static class StormRocModel extends EntityModel<RocState> {
        private final ModelPart body;
        private final ModelPart neck;
        private final ModelPart head;
        private final ModelPart rightWing;
        private final ModelPart leftWing;
        private final ModelPart rightTip;
        private final ModelPart leftTip;
        private final ModelPart rightLeg;
        private final ModelPart leftLeg;

        public StormRocModel(ModelPart root) {
            super(root);
            this.body = root.getChild("body");
            this.neck = root.getChild("neck");
            this.head = this.neck.getChild("head");
            this.rightWing = root.getChild("right_wing");
            this.leftWing = root.getChild("left_wing");
            this.rightTip = this.rightWing.getChild("right_wing_tip");
            this.leftTip = this.leftWing.getChild("left_wing_tip");
            this.rightLeg = root.getChild("right_leg");
            this.leftLeg = root.getChild("left_leg");
        }

        @Override
        public void setupAnim(RocState state) {
            super.setupAnim(state);
            float age = state.ageInTicks;
            if (state.flying) {
                float flap = Mth.sin(age * 0.35F) * 0.6F;
                this.rightWing.zRot = flap;
                this.leftWing.zRot = -flap;
                this.rightTip.zRot = flap * 0.7F;
                this.leftTip.zRot = -flap * 0.7F;
                this.rightLeg.xRot = 1.1F;
                this.leftLeg.xRot = 1.1F;
            } else {
                // Folded wings, a slow walk.
                this.rightWing.zRot = -1.2F;
                this.leftWing.zRot = 1.2F;
                this.rightWing.yRot = 0.5F;
                this.leftWing.yRot = -0.5F;
                this.rightTip.zRot = 2.4F;
                this.leftTip.zRot = -2.4F;
                float pos = state.walkAnimationPos;
                float speed = Math.min(1.0F, state.walkAnimationSpeed);
                this.rightLeg.xRot = Mth.cos(pos * 0.6F) * 0.8F * speed;
                this.leftLeg.xRot = -Mth.cos(pos * 0.6F) * 0.8F * speed;
            }
            this.neck.yRot = state.ridden ? 0.0F : state.yRot * DEG * 0.5F;
            if (state.ridden) {
                // Stretch the neck out forward and low so the head and crest stay below the rider's eye line.
                this.neck.xRot = 1.35F;
                this.head.xRot = -1.1F;
            }
            this.body.xRot = state.flying ? 0.1F : 0.0F;
        }
    }

    // --- Veyr, the Tempest Regent ----------------------------------------------------------------------------------

    public static class VeyrModel extends EntityModel<VeyrState> {
        private final ModelPart torso;
        private final ModelPart head;
        private final ModelPart rightArm;
        private final ModelPart leftArm;
        private final ModelPart rightPauldron;
        private final ModelPart leftPauldron;
        private final ModelPart cape;
        private final ModelPart ring;

        public VeyrModel(ModelPart root) {
            super(root);
            this.torso = ModLayers.path(root, "legs/torso");
            this.head = this.torso.getChild("head");
            this.rightArm = this.torso.getChild("right_arm");
            this.leftArm = this.torso.getChild("left_arm");
            this.rightPauldron = this.torso.getChild("right_pauldron");
            this.leftPauldron = this.torso.getChild("left_pauldron");
            this.cape = this.torso.getChild("cape");
            this.ring = this.torso.getChild("storm_ring");
        }

        @Override
        public void setupAnim(VeyrState state) {
            super.setupAnim(state);
            float age = state.ageInTicks;
            float a = state.assemble;
            // The armour assembles from the ground up, piece by piece, as the lightning strikes.
            this.cape.visible = a > 0.2F;
            this.rightArm.visible = a > 0.4F;
            this.leftArm.visible = a > 0.4F;
            this.rightPauldron.visible = a > 0.6F;
            this.leftPauldron.visible = a > 0.6F;
            this.head.visible = a > 0.8F;
            this.ring.visible = a >= 1.0F && !state.dying;
            this.ring.zRot = age * 0.05F;
            this.head.yRot = state.yRot * DEG;
            this.head.xRot = state.xRot * DEG;
            this.cape.xRot = 0.1F + Mth.sin(age * 0.12F) * 0.08F;
            this.rightPauldron.y += Mth.sin(age * 0.1F) * 0.8F;
            this.leftPauldron.y += Mth.sin(age * 0.1F + 1.0F) * 0.8F;
            this.rightArm.xRot = -0.25F;
            this.leftArm.xRot = Mth.sin(age * 0.08F) * 0.08F;
            float t = state.attackTicks;
            switch (state.attack) {
                case VeyrEntity.ATTACK_COMBO -> {
                    float swing = Mth.sin(Mth.clamp(t / 30.0F, 0.0F, 1.0F) * Mth.PI * 3.0F);
                    this.rightArm.xRot = -1.0F - swing * 1.0F;
                    this.torso.yRot = swing * 0.35F;
                }
                case VeyrEntity.ATTACK_LANCE -> {
                    float c = Math.min(1.0F, t / VeyrEntity.LANCE_CHARGE);
                    this.rightArm.xRot = -1.5F * c;
                    this.leftArm.xRot = -1.2F * c;
                    this.leftArm.zRot = -0.4F * c;
                }
                case VeyrEntity.ATTACK_VOLLEY, VeyrEntity.ATTACK_TORNADO -> {
                    float c = Math.min(1.0F, t / 8.0F);
                    this.rightArm.xRot = -2.9F * c;
                    this.leftArm.xRot = -2.9F * c;
                    this.rightArm.zRot = 0.3F * c;
                    this.leftArm.zRot = -0.3F * c;
                }
                case VeyrEntity.ATTACK_THUNDERSTEP -> this.rightArm.xRot = -1.7F;
                default -> {
                    this.torso.yRot = 0.0F;
                }
            }
            if (state.phase == VeyrEntity.PHASE_STUNNED) {
                this.torso.xRot = 0.6F;
                this.head.xRot = 0.5F;
                this.rightArm.xRot = 0.2F;
                this.leftArm.xRot = 0.2F;
            } else if (state.phase == VeyrEntity.PHASE_CONDUCTION || state.phase == VeyrEntity.PHASE_LAST_THUNDER) {
                this.rightArm.xRot = -3.0F;
                this.leftArm.xRot = -2.6F;
                this.leftArm.zRot = -0.5F;
            }
            if (state.dying) {
                this.torso.xRot = -0.3F;
                this.rightArm.zRot = 0.9F;
                this.leftArm.zRot = -0.9F;
            }
        }
    }

    // --- Storm Conductor -------------------------------------------------------------------------------------------

    public static class StormConductorModel extends EntityModel<ConductorState> {
        private final ModelPart rod;
        private final ModelPart tip;

        public StormConductorModel(ModelPart root) {
            super(root);
            this.rod = root.getChild("rod");
            this.tip = this.rod.getChild("tip");
        }

        @Override
        public void setupAnim(ConductorState state) {
            super.setupAnim(state);
            // Lowered, the rod is sunk into its base; raised, it stands at full height.
            this.rod.y += (1.0F - state.raised) * 24.0F;
            this.tip.yRot = state.ageInTicks * 0.1F;
        }
    }
}
