package com.starforged.sun;

import com.starforged.Starforged;
import net.minecraft.sounds.SoundEvent;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

/** Every sound of the Sunforged expansion (files generated by tools/gen_sounds.py). */
public final class SunSounds {
    public static final DeferredRegister<SoundEvent> SOUNDS = DeferredRegister.create(ForgeRegistries.SOUND_EVENTS, Starforged.MODID);

    // World
    public static final RegistryObject<SoundEvent> BRAZIER_IGNITE = register("block.solar_brazier.ignite");
    public static final RegistryObject<SoundEvent> SUN_SEAL_OPEN = register("block.sun_seal.open");
    public static final RegistryObject<SoundEvent> VENT_ERUPT = register("block.sunfire_vent.erupt");
    public static final RegistryObject<SoundEvent> SUN_ALTAR_ACTIVATE = register("block.sun_altar.activate");
    public static final RegistryObject<SoundEvent> GATEWAY_TRAVEL = register("block.solar_gateway.travel");
    public static final RegistryObject<SoundEvent> GATEWAY_FORM = register("item.solar_key.forge");

    // Items
    public static final RegistryObject<SoundEvent> LANCE_DASH = register("item.solar_lance.dash");
    public static final RegistryObject<SoundEvent> GREATSWORD_FLARE = register("item.flare_greatsword.flare");
    public static final RegistryObject<SoundEvent> PHOENIX_BOW_SHOOT = register("item.phoenix_bow.shoot");
    public static final RegistryObject<SoundEvent> SCEPTER_SUMMON = register("item.helios_scepter.summon");
    public static final RegistryObject<SoundEvent> CHAKRAM_THROW = register("item.cinder_chakram.throw");
    public static final RegistryObject<SoundEvent> FLASK_BURST = register("item.sunburst_flask.burst");
    public static final RegistryObject<SoundEvent> REBIRTH = register("item.phoenix_mantle.rebirth");
    public static final RegistryObject<SoundEvent> EGG_HATCH = register("item.phoenix_egg.hatch");

    // Creatures
    public static final RegistryObject<SoundEvent> IMP_AMBIENT = register("entity.cinder_imp.ambient");
    public static final RegistryObject<SoundEvent> IMP_HURT = register("entity.cinder_imp.hurt");
    public static final RegistryObject<SoundEvent> IMP_DEATH = register("entity.cinder_imp.death");
    public static final RegistryObject<SoundEvent> CRAWLER_AMBIENT = register("entity.magma_crawler.ambient");
    public static final RegistryObject<SoundEvent> CRAWLER_DEATH = register("entity.magma_crawler.death");
    public static final RegistryObject<SoundEvent> HOUND_AMBIENT = register("entity.ember_hound.ambient");
    public static final RegistryObject<SoundEvent> HOUND_GROWL = register("entity.ember_hound.growl");
    public static final RegistryObject<SoundEvent> HOUND_DEATH = register("entity.ember_hound.death");
    public static final RegistryObject<SoundEvent> KNIGHT_AMBIENT = register("entity.ashen_knight.ambient");
    public static final RegistryObject<SoundEvent> KNIGHT_BLOCK = register("entity.ashen_knight.block");
    public static final RegistryObject<SoundEvent> KNIGHT_DEATH = register("entity.ashen_knight.death");
    public static final RegistryObject<SoundEvent> PHOENIX_AMBIENT = register("entity.solar_phoenix.ambient");
    public static final RegistryObject<SoundEvent> PHOENIX_CRY = register("entity.solar_phoenix.cry");

    // Boss
    public static final RegistryObject<SoundEvent> WARDEN_ROAR = register("entity.sun_warden.roar");
    public static final RegistryObject<SoundEvent> WARDEN_HURT = register("entity.sun_warden.hurt");
    public static final RegistryObject<SoundEvent> WARDEN_DEATH = register("entity.sun_warden.death");
    public static final RegistryObject<SoundEvent> WARDEN_FLARE = register("entity.sun_warden.flare");
    public static final RegistryObject<SoundEvent> WARDEN_BEAM = register("entity.sun_warden.beam");
    public static final RegistryObject<SoundEvent> WARDEN_PILLAR = register("entity.sun_warden.pillar");
    public static final RegistryObject<SoundEvent> WARDEN_SLAM = register("entity.sun_warden.slam");
    public static final RegistryObject<SoundEvent> WARDEN_SUPERNOVA = register("entity.sun_warden.supernova");
    public static final RegistryObject<SoundEvent> PYLON_SHATTER = register("entity.solar_pylon.shatter");

    private static RegistryObject<SoundEvent> register(String name) {
        return SOUNDS.register(name, () -> SoundEvent.createVariableRangeEvent(Starforged.id(name)));
    }

    private SunSounds() {
    }
}
